### ISSUE TITLE
API does not enforce validation of required fields in nested items

### ISSUE THREAD

**Issue by LN-vchopra** [directus/api#855] opened 2019-03-26 21:28 UTC
# Bug Report

## Steps to Reproduce

1. Create a collection "Carousel"
2. Click another collection "Carousel Items" with Title, Image and Sort (all required) fields.
3. Update Carousel Collection to include a O2M field "Carousel Items"
4. Create a new Carousel object.
5. Click on Add New Carousel Item
6. Enter Title, leave Image and sort blank.
7. Save Carousel Item.

## Expected Behavior

Either on the Carousel Slide modal or on saving carousel, the system should error out saying - required fields are missing.

## Actual Behavior

System allows storing null values for fields marked as required.

## Other Context & Screenshots
![Screen Shot 2019-03-26 at 2 26 01 PM](https://user-images.githubusercontent.com/44380643/55034700-54bee080-4fd3-11e9-9035-92f16fdc2f31.png)
![Screen Shot 2019-03-26 at 2 25 52 PM](https://user-images.githubusercontent.com/44380643/55034701-54bee080-4fd3-11e9-9f2f-177dff3154c9.png)
![Screen Shot 2019-03-26 at 2 27 04 PM](https://user-images.githubusercontent.com/44380643/55034702-54bee080-4fd3-11e9-96d3-a5a513655991.png)

## Technical Details

- Device: Desktop
- OS: MacOS 10.14.3
- Browser: Firefox
- Directus App: 7.0.19
- Directus API: 2.0.18
- Install Method: cloned `master` branch of `directus/directus`

**Comment by theharshin** [comment] 2019-03-27 07:43
This is a known issue & relates to this: https://github.com/directus/api/issues/455

**Comment by benhaynes** [comment] 2019-04-25 15:05
This isn't just related, it seems like a duplicate of #455. I'm closing this one in preference of the original, but all of this info has been linked to that ticket for reference.

**Closed by benhaynes** 2019-04-25 15:05 UTC
Labels: bug, duplicate
