### ISSUE TITLE
Installation creates config file with wrong name making it impossible to login

### ISSUE THREAD

**Issue by arc4nis8** [directus/api#1449] opened 2019-11-19 15:09 UTC
# Bug Report

## Steps to Reproduce

Download Directus v8.0.0-rc.1 (git clone, or zip, doesnt matter) and configure the installation with the browser (navigate to /admin)

## Expected Behavior

After the installation is complete navigating to /admin should open the login form

## Actual Behavior

It opens the first step of the installation again and I cant get to the login form. Also in the console i get the error: GET http://cms.mydomain.loc/server/projects 503 (Service Unavailable)

## Technical Details

- Device: Desktop
- OS: Ubuntu 19
- Web Server: Nginx 1.15.9-0ubuntu1.1
- PHP Version: 7.2.0
- Database: MySQL 5.7.28-0ubuntu0.19.04.2
- Install Method: cloned `master` branch

## Solution to the bug

The problem seems to be that the installer creates a `diretus/config/_.php` and a `diretus/config/__api.json` file. Renaming those files to `diretus/config/api.php` and `diretus/config/api_api.json` solves the problem, and I can login just fine.

I've tried the same installation steps with Directus v7.0.19 and the installer creates the `diretus/config/api.php` config file, named correctly, so it seems a bug with version 8 rc.

**Comment by bjgajjar** [comment] 2019-11-20 07:22
Hey @arc4nis8, Thanks for reporting the issue. But can you please provide the name of your project which you have configured at the installation time?

Below are the steps which I followed to replicate the issue. Though, I am not able to reproduce it.
- Clone the master repo in local
- Open it in the browser, which automatically redirects to the `installation` page.
- Configure the project and server details [ Add `Directus` as project name]
- After a successful configuration, the installation completes.
- APP will redirect to the login page.

Here, I am getting the `directus.php` [The name of my project] and `__api.json` file.

Let me know if I am missing any step. :)

**Comment by arc4nis8** [comment] 2019-11-20 12:26
I tried again and it works fine if I input the same Project Name and dont change the Project Key that is automatically generated, for example:
Project Name: Directus
Project Key: directus

Now, the problem is that if I input a different Project Name and Key for example:
Project Name: Directus
Project Key: _

It doesnt work, it generates the wrong config files: `__api.json` and `_.php` and it doesnt allow me to login.

I dont know why I put  `_` as the Project Key, I read somewhere that its the default one. Anyway it seems that its a bug to allow the browser installer an input that will break the installation.

**Comment by bjgajjar** [comment] 2019-11-20 12:29
Okay - yes. That can be an issue. I'll try to replicate this issue using the given scenario.

**Comment by bjgajjar** [comment] 2019-11-21 05:37
Fixed in https://github.com/directus/api/pull/1455

**Closed** 2019-11-21 05:37 UTC
Labels: bug
