### ISSUE TITLE
Error when creating new API Instance

### ISSUE THREAD

**Issue by BenjaminF1999** [directus/api#650] opened 2018-12-11 13:57 UTC
Hey there Directus Community,
a few days ago I set up the Directus Suite on my Debian 9 VPS successfully. Afterwards I wanted to create a new API Instance for a friend as follows:

> 1) Created a new file "api.[project-name].php" in the /config folder (obviously replacing [...] with the real project name.
> 2) I changed the value of the Database it is connecting to and filled in a new "secret_key" and "public_key".

Afterwards i headed to /admin in my webbrowser and tried to log into the new api instance, but it would just give me the error:

> Something is wrong with this instance’s server or database.
> 
> Try again later or login to another instance. 

Anyone knows how to fix this?
Thanks for any answer

**Comment by rijkvanzanten** [comment] 2018-12-11 15:38
Thanks! 

(For next time, the file contains every warning / error. Copy pasting the “last one” is enough :)

<details>
<summary>Full stack trace</summary>
<pre>
[2018-12-11 16:23:38] api[].ERROR: Directus\Authentication\Exception\InvalidTokenException: Invalid Authentication Token in /var/www/directus/src/core/Directus/Util/JWTUtils.php:36
Stack trace:
#0 /var/www/directus/src/core/Directus/Authentication/Provider.php(554): Directus\Util\JWTUtils::decode
#1 /var/www/directus/src/core/Directus/Authentication/Provider.php(218): Directus\Authentication\Provider->getTokenPayload
#2 /var/www/directus/src/core/Directus/Services/AuthService.php(193): Directus\Authentication\Provider->authenticateWithToken
#3 /var/www/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(99): Directus\Services\AuthService->authenticateWithToken
#4 /var/www/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(31): Directus\Application\Http\Middleware\AuthenticationMiddleware->authenticate
#5 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#6 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#7 [internal function]: Slim\DeferredCallable->__invoke
#8 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#9 /var/www/directus/src/core/Directus/Application/Http/Middleware/AuthenticationIgnoreOriginMiddleware.php(19): Slim\Route->Slim\{closure}
#10 [internal function]: Directus\Application\Http\Middleware\AuthenticationIgnoreOriginMiddleware->__invoke
#11 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#12 [internal function]: Slim\DeferredCallable->__invoke
#13 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#14 /var/www/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#15 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#16 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#17 [internal function]: Slim\DeferredCallable->__invoke
#18 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#19 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#20 /var/www/directus/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#21 /var/www/directus/vendor/slim/slim/Slim/App.php(515): Slim\Route->run
#22 /var/www/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#23 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#24 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#25 [internal function]: Slim\DeferredCallable->__invoke
#26 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#27 /var/www/directus/vendor/akrabat/rka-ip-address-middleware/src/IpAddress.php(93): Slim\App->Slim\{closure}
#28 [internal function]: RKA\Middleware\IpAddress->__invoke
#29 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#30 [internal function]: Slim\DeferredCallable->__invoke
#31 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#32 /var/www/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#33 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#34 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#35 [internal function]: Slim\DeferredCallable->__invoke
#36 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#37 /var/www/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#38 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#39 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#40 [internal function]: Slim\DeferredCallable->__invoke
#41 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#42 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#43 /var/www/directus/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack
#44 /var/www/directus/vendor/slim/slim/Slim/App.php(314): Slim\App->process
#45 /var/www/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#46 /var/www/directus/public/index.php(5): Directus\Application\Application->run [] []
</pre>
</details>


The issue sounds similar to https://github.com/directus/api/issues/635, could you confirm it's the same @BenjaminF1999?

**Comment by BenjaminF1999** [comment] 2018-12-11 15:40
@rijkvanzanten Thank you so much!
You are totally right, #635 is similar. Can you tell me how I can find errors like this, so I don't have to open another thread next time?
Again thank you very much!

**Comment by alrick** [comment] 2018-12-14 11:49
To add to this issue, I have the same problem, private_key and public_key are different in the two API in my case.
Can someone confirm that a second API instance with the **directus suite** is working with the last version ?

**Comment by WellingGuzman** [comment] 2018-12-14 20:54
I am going to give your steps a try @BenjaminF1999.

> To add to this issue, I have the same problem, private_key and public_key are different in the two API in my case.

@alrick both secret and public keys should be different and different from the public and secret key of another project/instance.

**Comment by WellingGuzman** [comment] 2018-12-14 21:18
> In order to reproduce this might help:
> 
> > 1. I installed the Directus Suite
> > 2. Created the required API instance /_/ and created a new api instace /name/ afterwards.
> > 3. I used the same private_key and public_key for both projects (both being a 256bit hexadecimal, just like "iA1AWMkbSvm73rz8mTj8pOY3hpA9YloS"). Note: Private_key and Public_key are different from each other, they are just the same in both projects.
> > 4. Tested both admin accounts in the APIs (both working fine)
> > 5. Created a new account in the NEW api instance /name/
> > 6. Tried to log into the new account and at this point Iam getting the error described above

Based on your steps are unclear where is exactly things going on. I followed as I believe things were going, but I found no error authenticating to new users.

How do you authenticate to the new instance? how do you pick the new instance.

It will help if you could create a video demonstrating how you set up the projects and when the error happens.

**Comment by BenjaminF1999** [comment] 2018-12-15 13:11
> 
> 
> > In order to reproduce this might help:
> > > 1. I installed the Directus Suite
> > > 2. Created the required API instance /_/ and created a new api instace /name/ afterwards.
> > > 3. I used the same private_key and public_key for both projects (both being a 256bit hexadecimal, just like "iA1AWMkbSvm73rz8mTj8pOY3hpA9YloS"). Note: Private_key and Public_key are different from each other, they are just the same in both projects.
> > > 4. Tested both admin accounts in the APIs (both working fine)
> > > 5. Created a new account in the NEW api instance /name/
> > > 6. Tried to log into the new account and at this point Iam getting the error described above
> 
> Based on your steps are unclear where is exactly things going on. I followed as I believe things were going, but I found no error authenticating to new users.
> 
> How do you authenticate to the new instance? how do you pick the new instance.
> 
> It will help if you could create a video demonstrating how you set up the projects and when the error happens.
@WellingGuzman 
Sure! I recorded a video showing all my steps:
https://www.youtube.com/watch?v=AO1P9K-1FU8&feature=youtu.be

I hope it helps solving the bug, because it would be so awesome to get Directus up and running on my system :)

Thank you very much for replying btw. I hope you are having a great day

**Comment by alrick** [comment] 2018-12-21 14:01
@rijkvanzanten @WellingGuzman @benhaynes 
So an update about this issue, I setup a new instance of Directus on a new fresh server I received today. This one is configured without Alias with Directus only on it.
I followed the same steps except the Alias part and used DocumentRoot instead.

And I got the same problem again, BUT I changed the configuration of the App to routerMode: "history" instead of "hash" and everything seems to work like a charm now.

So maybe it's an app issue afterall ?
I hope it helps you fix this issue.

PS : I'll be off the next two weeks so I can't follow this issue during this time, I wish you all a happy holiday season !

**Comment by WellingGuzman** [comment] 2018-12-28 22:02
I realized this is the same bug as https://github.com/directus/api/issues/635. I am closing this as duplicated.

I can now reproduce this bug. The issue is related to the API not loading the correct auth secret token for the specific auth token owner (non default only).

Thanks everyone that helps following this issue.

**Closed by WellingGuzman** 2018-12-28 22:02 UTC
Labels: duplicate, not reproducible
