### ISSUE TITLE
Migration to Directus 7 blocked by existing files in directus_files

### ISSUE THREAD

**Issue by We-St** [directus/api#529] opened 2018-10-27 21:38 UTC
## Version Info
  - Directus API version (Or commit hash): 7.0.4
  - Web server: Apache
  - OS name and version: Windows Server 2008

## Expected Behavior
The Directus docs read: "However, because Directus stores your content as pure SQL, that data is always portable between versions". This is not true for uploaded user content, which is stored in directus_files. There seems to be not automated way to copy data from Directus-internal tables.

I'd expect to:
1. Copy my database (including Directus tables of the former version)
2. Run the install wizard of Directus 7
3. Point the wizard to the copied database
4. The wizard alters the tables (while keeping the data)

Alternatively: a file export, file import feature.

## Actual Behavior
Pointint Directus 7 to an old DB will cause the installation wizard to show an error and not complete. There seems to be no way to migrate files between versions.

## Steps to Reproduce
 1. Point the Directus 7 install page to an existing Directus 6.* data base

**Comment by WellingGuzman** [comment] 2018-10-29 13:53
Hey @We-St, At the moment there's no "official" way to upgrade from 6 to 7 yet.

There has been changes in the tables schemas, how extensions works, and the directory structure is different, It won't be a easy task to upgrade.

If someone is willing to create this "export" or upgrade script, I can help you get it done.

**Comment by benhaynes** [comment] 2018-10-29 17:00
`directus_files` is not a requirement of data portability — your files are on the server (or wherever the storage adapter is set to). The issue is not the system table, it's how to do bulk (re)uploads of the actual Files. This could be done in batches (you can drag multiple files at a time into File Library) or through a new feature (eg: FTP upload).

From v7+ this won't be an issue since we have a set versionless schema, but to get there we had to make some sacrifices with upgrades from previous version.

As Welling said, if someone wants to draft a script to map/migrate v6 system data to v7 we'll gladly take a look... but unfortunately our internal Core team doesn't have time to work on this.

I'll close this since it's not something we'll be able to work on and I think a "Bulk FTP Upload" would solve this specific case. Happy to continue the discussion though!

**Closed by benhaynes** 2018-10-29 17:00 UTC
