### ISSUE TITLE
Permission denied from directus_users when using translation interface

### ISSUE THREAD

**Issue by panbanda** [directus/api#1207] opened 2019-08-20 13:30 UTC
I have a site that is setup using the standard recommendation for translation (a separate table with a language/m2o field).  Let's use this as an example:

- diseases
- disease_translations

I have the translations interface on the `diseases` collection.  Next steps to follow:

- create a new user role
- assign a user
- sign in as that user
- try to update the diseases collection translation and you will see this error: "Updating item from "directus_users" collection was denied"

However, this is only in the `diseases` editor.  If I try and edit the `disease_translation` collection (same entry) it allows me to update it.  I tried the default user permissions with the install as well as the following configuration:

![Screen Shot 2019-08-20 at 16 25 09](https://user-images.githubusercontent.com/150944/63351020-261d1a00-c367-11e9-8960-c585a57b1b30.jpg)

If I assign full permission to the user row the denial comes from `directus_user_roles` instead.

This seems to be related to #723 but shows up when using the translation interface.

## Technical Details

- OS: Ubuntu
- Database: MySQL 8
- Install Method: cloned master

**Comment by urvashithakar** [comment] 2019-08-22 10:40
Hello @panbanda,

Not able to replicate this issue. Can you please confirm that you are using the latest version ?

**Comment by panbanda** [comment] 2019-08-25 07:48
Greetings, yes I am actually using the latest version as of 2 days ago.

**Comment by urvashithakar** [comment] 2019-08-26 06:51
Hi @panbanda,
I am not able to reproduce it in Directus Live demo as well as in my local env. So if you could provide SQL dump data, it will be great help to debug this issue. You can contact me in directus slack channel if your SQL is private. You can find @urvashi in http://directus.chat .

**Comment by Niekvan** [comment] 2019-08-26 14:47
Exactly the same issue for me. I contacted you in slack @urvashithakar

**Comment by bjgajjar** [comment] 2019-08-27 11:42
Fixed in #1221

**Closed** 2019-08-27 11:42 UTC
Labels: bug
