### ISSUE TITLE
v8.3.1 files interface with Required on a Single collection broken

### ISSUE THREAD

**Issue by everyx** [directus/api#1620] opened 2020-01-05 13:45 UTC
Hi, 

If i use a files interface and checked `required` option on a collection with `Single` option checked, I will get a `xxx: the value should not be blank` even if I have set it before.

I have reproduce on directus demo app.

![bug](https://user-images.githubusercontent.com/1665522/71781007-b00f0c00-3004-11ea-8f24-1c85f385965b.gif)

**Comment by rijkvanzanten** [comment] 2020-01-06 20:55
@bjgajjar we talked about this before, but I can't find the issue about it. When the app passes `null` or `[]` for a o2m that already has a value, the API shouldn't consider it empty.

**Comment by rijkvanzanten** [comment] 2020-01-06 22:27
Found it!


Duplicate of https://github.com/directus/api/issues/1502

**Closed by rijkvanzanten** 2020-01-06 22:27 UTC
Labels: bug
