### ISSUE TITLE
Error on login "Directus\Util\DateTimeUtils::createFromDateTime() must be an instance of DateTime"

### ISSUE THREAD

**Issue by xJoeyv** [directus/api#532] opened 2018-10-28 17:12 UTC
# Bug Report
When logging in I will receive a error that results of 

```
[2018-10-28 13:00:05] api[_].ERROR: TypeError: Argument 1 passed to Directus\Util\DateTimeUtils::createFromDateTime() must be an instance of DateTime, boolean given, called in C:\laragon\www\joeydvries\content\src\core\Directus\Util\DateTimeUtils.php on line 123 and defined in C:\laragon\www\joeydvries\content\src\core\Directus\Util\DateTimeUtils.php:96
Stack trace:
#0 C:\laragon\www\joeydvries\content\src\core\Directus\Util\DateTimeUtils.php(123): Directus\Util\DateTimeUtils::createFromDateTime(false)
#1 C:\laragon\www\joeydvries\content\src\core\Directus\Util\DateTimeUtils.php(109): Directus\Util\DateTimeUtils::createDateFromFormat('Y-m-d H:i:s', 'NULL', 'UTC')
#2 C:\laragon\www\joeydvries\content\src\core\Directus\Database\Schema\SchemaManager.php(568): Directus\Util\DateTimeUtils::createFromDefaultFormat('NULL', 'UTC')
#3 C:\laragon\www\joeydvries\content\src\core\Directus\Database\Schema\SchemaManager.php(268): Directus\Database\Schema\SchemaManager->createFieldFromArray(Array)
#4 C:\laragon\www\joeydvries\content\src\core\Directus\Database\TableGateway\BaseTableGateway.php(998): Directus\Database\Schema\SchemaManager->getFields('directus_activi...')
#5 C:\laragon\www\joeydvries\content\src\core\Directus\Database\TableGateway\BaseTableGateway.php(279): Directus\Database\TableGateway\BaseTableGateway->parseRecordValuesByType(Array)
#6 C:\laragon\www\joeydvries\content\src\core\Directus\Database\TableGateway\BaseTableGateway.php(817): Directus\Database\TableGateway\BaseTableGateway->find('3')
#7 C:\laragon\www\joeydvries\content\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(276): Directus\Database\TableGateway\BaseTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#8 C:\laragon\www\joeydvries\content\src\core\Directus\Database\TableGateway\DirectusActivityTableGateway.php(66): Zend\Db\TableGateway\AbstractTableGateway->insertWith(Object(Zend\Db\Sql\Insert))
#9 C:\laragon\www\joeydvries\content\src\core\Directus\Services\AuthService.php(56): Directus\Database\TableGateway\DirectusActivityTableGateway->recordLogin('1')
#10 C:\laragon\www\joeydvries\content\src\endpoints\Auth.php(49): Directus\Services\AuthService->loginWithCredentials('admin@example.c...', 'joe123')
#11 [internal function]: Directus\Api\Routes\Auth->authenticate(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#12 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(41): call_user_func(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#13 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#14 C:\laragon\www\joeydvries\content\src\core\Directus\Application\Http\Middleware\TableGatewayMiddleware.php(25): Slim\Route->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#15 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#16 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\TableGatewayMiddleware), Array)
#17 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#18 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#19 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#20 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\Route.php(334): Slim\Route->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#21 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\App.php(515): Slim\Route->run(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#22 C:\laragon\www\joeydvries\content\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\App->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#23 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#24 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\IpRateLimitMiddleware), Array)
#25 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#26 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#27 C:\laragon\www\joeydvries\content\vendor\akrabat\rka-ip-address-middleware\src\IpAddress.php(93): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#28 [internal function]: RKA\Middleware\IpAddress->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#29 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(RKA\Middleware\IpAddress), Array)
#30 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#31 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#32 C:\laragon\www\joeydvries\content\src\core\Directus\Application\Http\Middleware\CorsMiddleware.php(66): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#33 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#34 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\CorsMiddleware), Array)
#35 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#36 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#37 C:\laragon\www\joeydvries\content\src\core\Directus\Application\Http\Middleware\ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#38 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#39 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\ResponseCacheMiddleware), Array)
#40 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#41 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#42 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#43 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\App.php(406): Slim\App->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#44 C:\laragon\www\joeydvries\content\vendor\slim\slim\Slim\App.php(314): Slim\App->process(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#45 C:\laragon\www\joeydvries\content\src\core\Directus\Application\Application.php(161): Slim\App->run(false)
#46 C:\laragon\www\joeydvries\content\data\index.php(5): Directus\Application\Application->run()
#47 {main} [] []
```

## Steps to Reproduce

1. Go to your login page of your application
2. Fill in your **Correct** details
3. Click "Sign in"

## Expected Behavior
Login into Dashboard

## Actual Behavior
Gives a unknown error

## Other Context & Screenshots

This is the newest Directus API cloned from the Repo

## Technical Details

- Web Server: Apache
- PHP Version: PHP 7.1.20 (cli) (built: Jul 19 2018 08:59:55) ( ZTS MSVC14 (Visual C++ 2015) x64 )
- Database Type: MariaDB
- Database Version: 10.2.18-MariaDB - MariaDB Server
- Install Method: Cloned

**Comment by WellingGuzman** [comment] 2018-10-29 13:42
Duplicated issue. I am closing this in favor of #531.

**Comment by rijkvanzanten** [comment] 2018-10-29 13:48
This is caused by something else though @WellingGuzman isn't it? #531 is when you use a specific value as a default, this is when logging in in general

**Comment by xJoeyv** [comment] 2018-10-29 14:11
This is when logging in when I setup a new api. @WellingGuzman

**Comment by WellingGuzman** [comment] 2018-10-29 15:23
It's the same issue, but with different value. The problem you are experience it's because you are using MariaDB, and somehow the default value still `NULL` (as string) instead of `null` as a type.

I opened this ticket to follow up this bug: https://github.com/directus/api/issues/535

**Closed by WellingGuzman** 2018-10-29 15:23 UTC
Labels: duplicate
