### ISSUE TITLE
Multiple conditional filtering returns exceptions

### ISSUE THREAD

**Issue by cdwmhcc** [directus/api#1067] opened 2019-06-28 17:16 UTC
Bug Report

## Steps to Reproduce
1、Creat collection ` blog `:

Name| Type
------------ | -------------
title |  text-input
description | text-area 
isflag | toggle 

2、Add some entries:

Title | isflag | Description
------------ | ------------- | -------------
Hello Word |  0  |  This is a beautiful world. 
Announcing Prisma Day  |  0  |  World Programmer Carnival Day
Hello Directus  |  1  |  A great headless CMS

``` javascript
let searchkey = 'Hello'
let isflag = null

this.client.getItems("blog",{
    filter:{
        isflag: {
            eq: 0
         },
         title:{
             logical:'or',
             contains: searchkey 
         },
         description:{
             logical:'or',
             contains:  searchkey 
         },
     },
     limit: 50,
     fields: "*.*"
})
```

When the isflag value is empty, everything is normal. When the isflag value is 0 or 1, the result is inaccurate.

Isflag can also be other fields, such as categories:

``` javascript
let searchkey = 'Hello'
let category = '1,2,3,8'

this.client.getItems("blog",{
    filter:{
        "category.id": {
            in:  category 
         },
         title:{
             logical:'or',
             contains: searchkey 
         },
         description:{
             logical:'or',
             contains: searchkey 
         },
     },
     limit: 50,
     fields: "*.*"
})
```

## Expected Behavior
The correct filtering results can be returned

## Actual Behavior

Multiple conditional filtering returns exceptions

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/8030134/60359387-851b7e00-9a0b-11e9-9ea1-cce53199730f.png)
![image](https://user-images.githubusercontent.com/8030134/60359418-93699a00-9a0b-11e9-9a02-eb25853193b5.png)
![image](https://user-images.githubusercontent.com/8030134/60360703-ebee6680-9a0e-11e9-982b-7f7513a95e74.png)

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.2.1]
- APP Version: [7.6.1]
- Install Method: [cloned `master` branch]

**Comment by bjgajjar** [comment] 2019-07-01 06:24
Hey @cdwmhcc 

It seems that the result you are getting is the correct one.

Below is your data.
![image](https://user-images.githubusercontent.com/19200178/60414520-05053c00-9bf6-11e9-9995-28f1e8ce96cb.png)

And here is your condition;
> ```js
> let searchkey = 'Hello'
> let isflag = null
> 
> this.client.getItems("blog",{
>     filter:{
>         isflag: {
>             eq: 0
>          },
>          title:{
>              logical:'or',
>              contains: searchkey 
>          },
>          description:{
>              logical:'or',
>              contains:  searchkey 
>          },
>      },
>      limit: 50,
>      fields: "*.*"
> })
> ```
> 

Thus the query will be like; 
``` WHERE `blog`.`isflag` = 0 
  OR `blog`.`title` LIKE '%Hello%' 
  OR `blog`.`description` LIKE '%Hello%'  ```

You have "Hello" as the `title` in the 1st and the 3rd entries, and `isflag` is 0 for the 1st and 2nd entries.
That's why you are getting all the entries in the response.

Let me know if I am missing something :) Otherwise, it seems okay to me.

**Comment by cdwmhcc** [comment] 2019-07-01 08:18
I gave you my database on slack and you can see that I have a collection:soft.
Another collection: soft_categories.
The relationship between them is many to one. A category has many software.
Then let's see, I need to filter some of the software under a certain category.

```
let searchkey = 'Hello'
let isflag = null

this.client.getItems("blog",{
    filter:{
        “categories.id”: {
            eq: '2,3,4'
         },
         title:{
             logical:'or',
             contains: searchkey 
         },
         description:{
             logical:'or',
             contains:  searchkey 
         },
     },
     limit: 50,
     fields: "*.*"
})
```

In my opinion, the above filtering conditions are as follows:
Filter fields ` title  ` or `title_des` in collection `soft ` that contain `Hello` software, and they exist in the  categories.id : 2, 3, 4

But the above query,
```
"categories.id":{
eq:'2, 3, 4'
}
```
It didn't work.

**Comment by bjgajjar** [comment] 2019-07-01 13:35
After having a long conversation with @cdwmhcc  able to find out that it is related to #958

**Comment by bjgajjar** [comment] 2019-07-10 07:06
@rijkvanzanten 

Let me know are we supposed to develop [this](https://github.com/directus/api/issues/958#issuecomment-496886141) functionality or not. As we discussed in the slack channel user need to develop custom endpoint for this type of requirement.

For developing this we need to discuss the format first to differentiate the parameters of `or` and `and`.

I'll suggest we don't need to support this type of advanced filters as it can have infinite combinations and it may also create problem in joins.

Let me know your thoughts here :)

**Comment by cdwmhcc** [comment] 2019-07-10 13:05
@bjgajjar Thank you!

Current filters support only two conditional queries if or is used
For example:

This can be supported.
``` javascript
this.client.getItems("blog",{
    filter:{
         title:{
             logical:'or',
             contains: 'hello'
         },
         description:{
             logical:'or',
             contains: 'hello'
         },
     },
     fields: "*.*"
})
```

This is not supported.
``` javascript
this.client.getItems("blog",{
    filter:{
        “flag”: {
            eq:  1
         },
         title:{
             logical:'or',
             contains: 'hello'
         },
         description:{
             logical:'or',
             contains: 'hello'
         },
     },
     fields: "*.*"
})
```

The logic of webapp I'm working on is not complicated.
One of the filtering scenarios is:

![image](https://user-images.githubusercontent.com/8030134/60971206-34cee500-a356-11e9-8951-25107d521a22.png)

It is not possible at present.

**Comment by rijkvanzanten** [comment] 2019-07-10 15:08
This type of grouped filters is not possible in the API yet. Based on the comments above, what you are trying to do is (in pseudo code) `WHERE flag = 1 AND (title = 'hello' OR  description = 'hello')`.

@bjgajjar in that issue you linked, you said

> I found the problem. Will send the PR ASAP.

What's the status of that?

Generally speaking, I don't think there is one solution that works for all use cases. We would need to invent an updated way of sending the filters in the url params in order to make this grouping possible. For example, there's no way to differentiate between `WHERE a=1 AND (b=2 OR C=3)` and `WHERE (a=1 AND b=2) OR c=3` in the current structure of the URL params.

@cdwmhcc for the time being, you could use multiple queries and handle them with the promise.all method:

```js
async fetchItems() {
  const responses = await Promise.all([
    this.client.getItems('blog', {
      filter: { 
        title: { contains: 'hello' },
        flag: { eq: 1 }
      }
    }),

    this.client.getItems('blog', {
      filter: { 
        description: { contains: 'hello' },
        flag: { eq: 1 }
      }
    })
  ]);

  const items = [...responses[0].data, ...responses[1].data];
  // Do something with items
}
```

**Comment by benhaynes** [comment] 2019-07-10 15:12
Thanks Rijk. 

In accordance with our [80/20 rule](https://docs.directus.io/getting-started/contributing.html#_80-20-rule), I feel that for now Custom Endpoints (with custom SQL commands) should suffice for these more complex queries.

Unless @bjgajjar has a solution in mind, that is. 😉

**Comment by cdwmhcc** [comment] 2019-07-10 15:27
@rijkvanzanten 
Thank you very much!
I agree with you. I think this combination is the best solution.

However, requesting multiple interfaces at the same time can only be a temporary solution. If there is no development plan, I will simplify the filtering rules of my APP and use the simplest Q to query.

**Comment by cdwmhcc** [comment] 2019-07-10 15:33
> Thanks Rijk.
> 
> In accordance with our [80/20 rule](https://docs.directus.io/getting-started/contributing.html#_80-20-rule), I feel that for now Custom Endpoints (with custom SQL commands) should suffice for these more complex queries.
> 
> Unless @bjgajjar has a solution in mind, that is. 😉



> Thanks Rijk.
> 
> In accordance with our [80/20 rule](https://docs.directus.io/getting-started/contributing.html#_80-20-rule), I feel that for now Custom Endpoints (with custom SQL commands) should suffice for these more complex queries.
> 
> Unless @bjgajjar has a solution in mind, that is. 😉

I feel Directus needs a public roadmap
Some functions can be collected in it and sorted according to user feedback.

**Comment by rijkvanzanten** [comment] 2019-07-10 16:06
> I feel Directus needs a public roadmap

Any thoughts on where and how to structure it? It's hard to manage the roadmap exactly cause most features / improvements come from the community as a whole

**Comment by cdwmhcc** [comment] 2019-07-10 16:13
> roadmap
I've seen this product. Maybe it will help you?
https://www.productboard.com/features/portal?utm_source=referral&utm_medium=portal&utm_term=portal-root-301

**Comment by rijkvanzanten** [comment] 2019-07-10 17:58
Hmm, it looks kinda similar to what we're doing in the feature request project boards:

https://github.com/directus/app/projects/45
https://github.com/directus/api/projects/40

**Comment by cdwmhcc** [comment] 2019-07-10 18:01
> Hmm, it looks kinda similar to what we're doing in the feature request project boards:
> 
> https://github.com/directus/app/projects/45
> https://github.com/directus/api/projects/40

Yeah，The difference is that the decision makers are you.

**Comment by bjgajjar** [comment] 2019-07-11 04:46
@rijkvanzanten 

> What's the status of that?

I had found the problem and we all had a discussion in the slack channel to decide the flow. So I didn't start the changes as we had not any conclusion yet.

After having a look in depth; I found that maybe we need to go with the custom endpoints only.

> you could use multiple queries and handle them with the promise

Agree with you here.

**Comment by rijkvanzanten** [comment] 2019-07-11 15:59
I'll close the OP bug as a wontfix seeing that it's not a bug per se but a feature that doesn't exist yet. Feel free to open a feature request to discuss possible ways to implement a grouped filter structure

**Closed** 2019-07-11 15:59 UTC
Labels: wontfix
