### ISSUE TITLE
Problem with migrations on v8.4

### ISSUE THREAD

**Issue by mfcanovas** [directus/api#1661] opened 2020-01-17 00:30 UTC
# Bug Report

I can't upgrade from Directus 7 to Directus 8 because data type TYPE_USER_CREATED has been removed in [v8.4.0 commit](https://github.com/directus/directus/commit/c894e6730a20172c578457f54ad00516fdb583c9) and it's needed by 20191123053252_update_directus_files_field migration.

## Steps to Reproduce

- Upgrade from v7 to v8.4 (for example, by running directus/directus:v8-apache docker container)

- Go to login page

## Expected Behavior

User could be logged in

## Actual Behavior

Internal Server Error is shown

## Other Context & Screenshots

Error stack trace:

`[2020-01-17 00:14:45] api[_].ERROR: Error: Undefined class constant 'TYPE_USER_CREATED' in /var/directus/migrations/upgrades/20191123053252_update_directus_files_field.php:119
Stack trace:
#0 /var/directus/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(124): UpdateDirectusFilesField->change
directus/directus#1 /var/directus/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(375): Phinx\Migration\Manager\Environment->executeMigration
directus/directus#2 /var/directus/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(351): Phinx\Migration\Manager->executeMigration
directus/directus#3 /var/directus/src/core/Directus/Util/Installation/InstallerUtils.php(244): Phinx\Migration\Manager->migrate
directus/directus#4 /var/directus/src/core/Directus/Util/Installation/InstallerUtils.php(231): Directus\Util\Installation\InstallerUtils::runMigrationAndSeeder
directus/directus#5 /var/directus/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(13): Directus\Util\Installation\InstallerUtils::updateTables
directus/directus#6 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
directus/directus#7 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#8 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#9 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#10 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
directus/directus#11 /var/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
directus/directus#12 /var/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
directus/directus#13 /var/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
directus/directus#14 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
directus/directus#15 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#16 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#17 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#18 /var/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
directus/directus#19 /var/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
directus/directus#20 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
directus/directus#21 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#22 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#23 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#24 /var/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
directus/directus#25 [internal function]: RKA\Middleware\IpAddress->__invoke
directus/directus#26 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#27 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#28 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#29 /var/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
directus/directus#30 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
directus/directus#31 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#32 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#33 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#34 /var/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
directus/directus#35 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
directus/directus#36 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#37 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#38 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#39 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
directus/directus#40 /var/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
directus/directus#41 /var/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
directus/directus#42 /var/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
directus/directus#43 /var/directus/public/index.php(5): Directus\Application\Application->run [] []
`

## Technical Details

- Device: Desktop
- OS: MacOS 10.14.6
- Database: [eg: MySQL 8.0.12]
- Directus Release Version: v8.4.0
- Install Method: docker

**Comment by bjgajjar** [comment] 2020-01-20 10:36
Duplicate of https://github.com/directus/api/pull/1652
https://github.com/directus/api/pull/1653 will resolve this.

**Closed by bjgajjar** 2020-01-20 10:36 UTC
Labels: bug
