### ISSUE TITLE
API doesn't set default value

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1676] opened 2020-01-21 18:30 UTC
If I post `default_value: "1"` from the app, the API returns `default_value: null`. 

Could it be that the API doesn't cast the provided values to the datatype of the field (anymore) before setting the default value @bjgajjar? This used to work before.

The default value input in the app is a text-input, so all values will be provided as a string.

**Comment by bjgajjar** [comment] 2020-01-22 08:58
Duplicate of https://github.com/directus/api/issues/1668

**Closed by bjgajjar** 2020-01-22 08:58 UTC
Labels: bug

**Comment by ithiru** [comment] 2020-02-04 14:04
I took the tag 8.5.0 and tried this, I see the same issue. It is not persisting default value. This is the steps I followed.

git pull
git checkout v8.5.0
php bin/directus db:upgrade -N <project key> - Verified the migrations ran by checking the directus_migrations table.

Accessed the app via url, 
modified a field and set the default value.
Opened the same field again, it didn't save the default value.

Am I missing anything? Please assist

**Comment by benhaynes** [comment] 2020-02-04 14:45
Hey @ithiru — it's probably best to post on the referenced ticket so your question doesn't get overlooked: https://github.com/directus/api/issues/1668

Thanks!

**Comment by ithiru** [comment] 2020-02-04 14:55
@benhaynes  done, thanks!
