### ISSUE TITLE
Hooks are not being triggered. 

### ISSUE THREAD

**Issue by TJZenkai** [directus/api#1419] opened 2019-11-12 14:49 UTC
Just created a sample hook in api.php file, under actions. The hook does a post request when a item is added to collection named vanity_urls. The vanity_urls collection has two fields. source and destination.

> 'hooks' => [
>         'actions' => [
> 'item.create.vanity_urls' => function ($collectionName, $data) {
>                 $ch = curl_init();
>                 curl_setopt($ch, CURLOPT_URL, 'https://api.fastly.com/service/servid/dictionary/dictid/item');
>                 curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
>                 curl_setopt($ch, CURLOPT_POST, 1);
>                 curl_setopt($ch, CURLOPT_POSTFIELDS, "item_key=/" . $data['source'] . "&item_value=" . $data['destination']);
>                 $headers = array();
>                 $headers[] = 'Fastly-Key: keyashasjhas';
>                 $headers[] = 'Content-Type: application/x-www-form-urlencoded';
>                 curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
>                 $result = curl_exec($ch);
>                 if (curl_errno($ch)) {
>                     echo 'Error:' . curl_error($ch);
>                 }
>                 curl_close($ch);
>             },
>    ],
>    'filters' => [],
> ],

This hook is not sending the request after I create an item inside the collection. We tried to log details from inside the hook, but nothing is being logged at all, so this code is never being triggered. Any thing wrong with the hook itself? I tested the php curl command outside of hook and it works fine.

**Comment by bjgajjar** [comment] 2019-11-19 06:59
Hey @TJZenkai - Thanks for reporting the issue. We introduced the `Webhooks` in our latest version - to call a particular URL on a particular action.  

![image](https://user-images.githubusercontent.com/19200178/69123669-f269a180-0ac7-11ea-9bfe-8baca8b33a08.png)

And I'll take a look for the hook which is duplicate of https://github.com/directus/api/issues/1328

**Closed by bjgajjar** 2019-11-19 06:59 UTC
Labels: bug
