### ISSUE TITLE
what is the schema of API url, Not clearly mentioned in Documentation.

### ISSUE THREAD

**Issue by aynomjb** [directus/api#1544] opened 2019-12-11 12:09 UTC
Trying to visit : http://localhost/directus/api

by setting the Authorization Header: Bearer 
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTc1NzE0ODcwLCJ0eXBlIjoiYXV0aCIsImtleSI6IjczZWVkOTI0LTliNjYtNGZkNC05ZjY2LWE5MGU2Y2RmOTVhOCIsInByb2plY3QiOiJ0YXh3aW5ibG9nIn0.OC_wpjF3qm0Y9DuDNa-JdoGr6FjXgYQp1FVSKdNy-CE
```

```json
Response: {
    "error": {
        "code": 3,
        "message": "Unauthorized request",
        "class": "Directus\\Exception\\UnauthorizedException",
        "file": "C:\\wamp64\\www\\directus\\src\\helpers\\app.php",
        "line": 286
    }
}
```

Above token is generated by: `http://localhost/directus/taxwinblog/auth/authenticate`

### Response

```json
 {
    "data": {
        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTc2MDYzNTM1LCJ0eXBlIjoiYXV0aCIsImtleSI6IjczZWVkOTI0LTliNjYtNGZkNC05ZjY2LWE5MGU2Y2RmOTVhOCIsInByb2plY3QiOiJ0YXh3aW5ibG9nIn0.fW-vtcdQIeCmTZd5hCem4YyfBgZA1GYzjFesMlmrO-A",
        "user": {
            "id": "1",
            "status": "active",
            "role": "1",
            "first_name": "Admin",
            "last_name": "User",
            "email": "jadavananda.bordoloi@tax2win.in",
            "timezone": "UTC",
            "locale": "en-US",
            "locale_options": null,
            "avatar": null,
            "company": null,
            "title": null,
            "external_id": null,
            "theme": "auto",
            "2fa_secret": null
        }
    },
    "public": true
}
```

**Comment by bjgajjar** [comment] 2019-12-13 10:28
@aynomjb - From the given bug description; It seems like your project name is `taxwinblog` and you are trying to execute `/api` endpoint. We don't have any endpoint named `/api`.

When you are trying to execute the `{base_url}/api`; it will be considered as `{base_url}/{project_name}`. API will try to find the project named `api` and if it'll not found then try to create an unknown project - which is throwing an `Unauthorised access` error.

Can you please verify once that are you trying to fetch the `/api` endpoint or passing `/api` as a project name? 

@rijkvanzanten - Can you please check https://github.com/directus/api/pull/1416 and provide your inputs here?

**Comment by rijkvanzanten** [comment] 2019-12-13 15:14
Duplicate of https://github.com/directus/docs/issues/242

**Closed by rijkvanzanten** 2019-12-13 15:14 UTC
Labels: bug

**Comment by rijkvanzanten** [comment] 2019-12-13 15:15
@aynomjb please refrain from opening the same issue more than once. It's very annoying for us to triage and work with. We see all issues on all the repos, so even if you post in the wrong one, we'll transfer and go from there.
