### ISSUE TITLE
Thumbnail is not be deleted on the deletion of original image

### ISSUE THREAD

**Issue by binal-7span** [directus/api#1133] opened 2019-07-19 08:53 UTC
# Bug Report

Thumbnail is not be deleted when you delete the original image.

## Steps to Reproduce

1. Go to 'File Manager'
2. Delete any image
3. Thumbnail of that image will not be deleted.

## Expected Behavior
Thumbnail needs to be deleted when you delete the original image.

## Actual Behavior
Thumbnail is not be deleted on the deletion of the original image

## Technical Details

- Device: Desktop
- OS: Windows 8.1
- Web Server: Apache 2.4.33[WAMP]
- PHP Version: 7.2.4
- Database: MySQL 5.7.21
- Install Method: Cloned `master` branch

**Comment by bjgajjar** [comment] 2019-07-19 09:44
The logic for the path of the thumbnail is going to be changed as the issue is already in the feature request (#813). We might need to rework on this issue when we will make changes.

So I'll suggest let's move this as a feature request.

**Comment by benhaynes** [comment] 2019-07-19 14:34
We don't have a timeline for #813 yet (although I'd love to have it added in sooner)... so we shouldn't close this since we don't know how long until we can add the new thumbnailer. In the meantime, it seems like this should be resolved so that those thumbnails aren't taking up server space and inaccessible from the App/API.

If it's more efficient, we can do #813 at the same time that we resolve this bug.

**Closed as completed** 2019-08-27 13:29 UTC
Labels: enhancement
