### ISSUE TITLE
Multiple API Projects — Only the default works

### ISSUE THREAD

**Issue by konradwww** [directus/api#635] opened 2018-11-29 13:40 UTC
# Bug Report

## Steps to Reproduce

1. Go to 'http://localhost:8081/login' and  choose sign in into `second` API Endpoint
2. Click on login
3. See error "Server Error  Something is wrong with this instance’s server or database."

## Expected Behavior
No error
## Actual Behavior
The app doesn't work with other endpoint/project then `_` default

## Other Context & Screenshots
![directus_screenshot](https://user-images.githubusercontent.com/4331326/49225574-b33ccf00-f3e4-11e8-9b21-b8f9e9778246.png)

It looks like for some api routes the `app` uses the default project slug `_`
Please see screnshot which shows network connections and routes which are trying to connect to the default api endpoint without project name.
http://localhost:8080
http//localhost:8080/pages
http//localhost:8080/layouts
http//localhost:8080/interfaces

On the other hand here are some routes which include project name correcty:
http://localhost:8080/second/settings/fields

## Technical Details

- Device: Desktop 
- OS: MacOS 10.14.1
- Browser: Chrome Version 71.0.3578.75 (Official Build) beta (64-bit)
- Directus App: master
- Directus API: master
- Install Method: cloned master

**Comment by lingej** [comment] 2018-12-07 06:50
Thanks @honzabilek4 !

Access to /interfaces, /pages and /layouts ist possible without authorization!

But if Request Header contains "Authorization: Bearer sometoken" the (invalid ) token is checked against the default config. Result is 404 "User not found"

Joerg

**Comment by honzabilek4** [comment] 2018-12-07 08:37
@lingej ah yeah, thanks for clarification. Of course these are public.

**Comment by honzabilek4** [comment] 2018-12-10 09:50
@benhaynes, @WellingGuzman 
Can we push this up? It looks like a pretty severe bug to me.

**Comment by benhaynes** [comment] 2018-12-10 12:40
Absolutely, thanks for the reminder @honzabilek4 . I'll have Welling check this out now.

**Comment by WellingGuzman** [comment] 2018-12-10 13:35
I have been trying to replicate this issue without luck.

I have tried with:
- instances with the same email/password combination
- instances with the different email/password combination

Worked as expected. Can you all try removing/clearing the app site data (local storage and session storage)? I had a issue before with multiple instances where they were old data and cleaning that up fixes it.

**Comment by honzabilek4** [comment] 2018-12-10 18:51
@WellingGuzman,
This is not about email/password combination. The problem is in the JWT `secret_key` stored in api configuration files. The API environment works only if the `secret_key` is exactly the same as the default one in `api.php`.

**Comment by WellingGuzman** [comment] 2018-12-10 19:23
@honzabilek4 I read your comment above, what I am believing is that the app is not sending the old token from the default instance, and that's why you are getting unauthorized errors.

I recommended clearing because it might have those token lying around in cache.

If you go and authenticate using credentials to a non-default instance and try to use those endpoints directly and see if it fails.

The three instances I used to test this issue locally didn't have the same `secret_key` and the app worked as expected.

**Comment by honzabilek4** [comment] 2018-12-10 19:50
Okay,
so I've pulled the latest versions again and everything works with the exactly same setup.
I think we might close it right now.
Thanks @WellingGuzman!

**Comment by benhaynes** [comment] 2018-12-10 19:51
Awesome! Thanks for checking this out @honzabilek4 😄

**Comment by honzabilek4** [comment] 2018-12-26 15:14
Hi, 
I'm sorry but I have to reopen this issue, since the problem still occurs.
This time, I'm testing only the API using Postman. [v2.0.13]

1. I've created new api config with random `secret_key` different form the default one in `api.php`.
2. Querying the `/interfaces` endpoint **without** `Bearer` token in header **works perfectly**.
![screenshot 2018-12-26 at 15 48 34](https://user-images.githubusercontent.com/7890555/50449177-d72cfb00-0925-11e9-91f3-e1d3ecfc63bd.png)

3. However, when querying the api **with** `Bearer` it doesn't behave as a public endpoint. I'm trying to mimic the app behaviour here, so I'm logging in and using the returned JWT token with the request.
![screenshot 2018-12-26 at 16 00 24](https://user-images.githubusercontent.com/7890555/50449385-5f5fd000-0927-11e9-8b79-408adc0f1e84.png)
![screenshot 2018-12-26 at 15 59 40](https://user-images.githubusercontent.com/7890555/50449368-49520f80-0927-11e9-9e66-8163c7a282d6.png)

4. When changing the `secret_key` to same as in `api.php` and re-logging again (to get a new JWT signed with the changed key) **it works**, even when the `Bearer` token is present.
![screenshot 2018-12-26 at 16 06 47](https://user-images.githubusercontent.com/7890555/50449541-4dcaf800-0928-11e9-9dbe-97cdb0828d07.png)

It's the same problem as described above, but here it's not dependent on the APP. There are more solutions to this, but I think that public endpoints shouldn't care about `Bearer` token at all, rather than disallowing it. 
Another fix would be changing the javascript SDK to not include a token for these endpoints, but this seems less ideal.

Opinions @WellingGuzman, @rijkvanzanten ??

**Comment by rijkvanzanten** [comment] 2019-01-04 16:33
I agree @honzabilek4. The API should ignore the auth headers on public endpoints. The SDK is more of a fix than a solution.

**Comment by zyclonite** [comment] 2019-01-07 17:03
same problem here, user cannot login on other projects than the default one...
if no bearer token is send the shared enpoints are working

**Comment by benhaynes** [comment] 2019-01-07 17:55
We just discussed this internally. We for privacy reasons we can't make those root extension endpoints public, but @WellingGuzman has an idea of how to fix this while keeping those private. I've escalated this to `critical` and it's next on our docket.

**Comment by benhaynes** [comment] 2019-01-07 20:30
Thanks @WellingGuzman!!! 💪 

Can anyone who had reproduced this confirm that this commit resolves the issue? Once confirmed we can release the next version.

🔔 @zyclonite @konradwww @honzabilek4 @lingej

**Comment by zyclonite** [comment] 2019-01-08 08:33
the fix is working, thank you

**Comment by honzabilek4** [comment] 2019-01-08 09:35
Hi,
I did some manual testing on this. 
- Shared endpoints now aren't public, but require authentication to any project.   ✅
-  Tried to do multiple requests to these endpoints endpoints through Postman, belonging to one instance but different projects with different `secret_key`. ✅
- Tried to log in to the same projects through the app with uncleared/cleared cache each time. ✅

Everything appears to be working. 🎉

**Comment by WellingGuzman** [comment] 2019-01-09 13:13
Thanks for confirming this @zyclonite and @honzabilek4!

**Comment by zyclonite** [comment] 2019-01-09 13:35
@WellingGuzman sorry, but i found a problem now...

looks like the "public" pages verify the user is from the session (token) but if the user only exists in the particular project and not in the default (_) project, it returns a 404 user not found

either it should check against the correct database for the project or ignore the auth token at all i guess

**Comment by WellingGuzman** [comment] 2019-01-09 14:55
@zyclonite let me give this a shot.

**Comment by WellingGuzman** [comment] 2019-01-09 16:07
I am being playing around with this "global/shared" endpoints, and also aside from the issue loading the default db configuration instead of the token origin project, this means that using a static token, will always fails or resulting in an unexpected behavior because there's no way to tell where that token belongs without explicitly tells the API which one is it.

One way I am thinking to solve this, is implementing a "configuration" switcher, that depends on the auth token origin project. This is a bit complex solution, and It will only works with JWT token.

A quicker way will be implement this as a hotfix middleware that will only work for "shared" endpoints, but only on JWT token.

Unless we want to update the endpoints to add a way to specify the origin directly, to either use static token, load first the configuration based on this, or both.

I need to think more about this, as I will prefer to implement a proper "configuration" switcher, but a hotfix for the moment will do it.

**Comment by WellingGuzman** [comment] 2019-01-11 18:17
That only would solve the issue with static token not being able to tell which project it belongs to.

The main issue here is that the api should "switch" its configuration and objects to an specific project. For example, there's only one database connection object, and it's attached to the default project. Here is the part that needs to be solve, using the other endpoints you know which is the project beforehand and pick the right connection because the project name is in the url.

There should be a refactor where the connection shouldn't be loaded until the app knows which project is pointing to.

**Comment by WellingGuzman** [comment] 2019-02-04 19:39
Hey everyone,

We've been discussing this bug for a while and we came up with a solution by getting the project name from the JWT token on all the shared/global endpoints such as `/interfaces`.

If everyone could try this fix (currently on `master` branch) and confirm is working that would be great.

I've been testing for a while and I haven't found any issue, but we all know as soon as someone else test it, they could find a bug, if there's any.

Ref: https://github.com/directus/api/commit/0e5a715c210b8f45f6a3971685d4b0438b1693eb

**Comment by honzabilek4** [comment] 2019-02-04 20:47
Thanks @welling! 
I’ll be able to give it a shot on Thursday at earliest.

**Comment by zyclonite** [comment] 2019-02-04 22:20
i tried 2.0.17 as well as the two commits after... but i cannot even login because the /server/ping resource gets me already a 401 "Unauthorized request"

**Comment by WellingGuzman** [comment] 2019-02-06 13:27
@zyclonite the `master` branch should be working now. we will appreciate it any one could test the `master` branch before next release.

I fixed the `/server/ping` issue here: https://github.com/directus/api/commit/dbb48782f221a14ece2b1ff34592b9321d08a1b5

**Comment by zyclonite** [comment] 2019-02-06 14:34
@WellingGuzman tested the master at this id https://github.com/directus/api/tree/58304733dd3007d952fd589577dce868740f4fcd now and it worked.

**Comment by benhaynes** [comment] 2019-02-08 21:05
We'd love to hear from a few more folks to ensure this is working — but since this patch has been released we'll close the ticket so things don't get confusing.

If anyone has any issues with using multiple projects just let us know!

**Closed by benhaynes** 2019-02-08 21:05 UTC
Labels: bug, fixed

**Comment by alrick** [comment] 2019-02-22 13:53
I'm a bit late but I can confirm the problem is solved with the latest update !
