### ISSUE TITLE
User behaviour like relational field

### ISSUE THREAD

**Issue by maettyhawk** [directus/api#656] opened 2018-12-16 10:57 UTC
I created a members collection referencing users in directus_users table (using User content type). When I request the items of members with the API it's not possible to resolve the users relation. I'm only getting the users id.
As a workaround I'm now using a M2O relation to resolve the user details, but actually I expected the User type to behave like a relation.

**Comment by shealavington** [comment] 2018-12-16 22:21
Does the user trying to read the table have permissions to read the Directus_user table? And are you also appending `?fields=*.*` to get related information?

**Comment by maettyhawk** [comment] 2018-12-16 22:44
I was using the admin user and I also appended `?fields=*.*` in order to resolve the relation.

**Comment by shealavington** [comment] 2018-12-16 23:11
And just to confirm when you say you used the user content type, you mean you used the interface of `User`?

**Comment by maettyhawk** [comment] 2018-12-17 15:14
Yes, exactly.

**Comment by WellingGuzman** [comment] 2018-12-17 20:36
Hey @maettyhawk, can you share the schema you are using so we can take a look why there's not a relationship in your user field?

**Comment by maettyhawk** [comment] 2018-12-17 21:39
Hey @WellingGuzman, here's how to reproduce:
- add new collection (f.e. "member")
- add field "user" using the User interface (=> collection has only two fields: id and user)
- create new item -> select existing user
- access /items/member?fields=*.* (I also tried /items/member?fields=* and /items/member?fields=*.*.*)
- response (user is not getting resolved): 
`{
  "data": [
    {
      "id": 1,
      "user": 1
    }
  ]
}`

**Comment by rijkvanzanten** [comment] 2018-12-18 21:53
I believe this is a duplicate of https://github.com/directus/api/issues/495

**Comment by maettyhawk** [comment] 2018-12-19 13:20
You‘re right, @rijkvanzanten.

**Comment by WellingGuzman** [comment] 2018-12-19 13:51
Thanks for clarifying @maettyhawk. I will close this in favor of #495.

**Comment by WellingGuzman** [comment] 2018-12-19 14:14
Hey @maettyhawk can you give the schema you are using that is having this issue. I confirmed this was already implemented.

**Comment by maettyhawk** [comment] 2018-12-19 15:56
@WellingGuzman I think I‘m not sure what you mean with the scheme. 😕

**Comment by benhaynes** [comment] 2018-12-19 15:59
Either a full database dump (ideal if possible). Or the table/column architecture and the values within `directus_relations`. @maettyhawk

**Comment by rijkvanzanten** [comment] 2018-12-19 15:59
@maettyhawk The way you setup the database, eg what fields in use etc. You can share a full SQL dump (if you don't have any private info in it) if you want. That allows @WellingGuzman to reproduce your full setup 1 to 1 to be able to see what's up

**Comment by rijkvanzanten** [comment] 2018-12-19 15:59
Beat me to it by 18 seconds @benhaynes 😄

**Comment by maettyhawk** [comment] 2018-12-19 16:14
Here you are!
[dump.zip](https://github.com/directus/api/files/2695624/dump.zip)

> 
> Hey @WellingGuzman, here's how to reproduce:
> 
>     * add new collection (f.e. "member")
> 
>     * add field "user" using the User interface (=> collection has only two fields: id and user)
> 
>     * create new item -> select existing user
> 
>     * access `/items/member?fields=*.* `(I also tried `/items/member?fields=*` and `/items/member?fields=*.*.*`)
> 
>     * response (user is not getting resolved):
>       `{ "data": [ { "id": 1, "user": 1 } ] }`
> 
> 
> The schema of the user field is the interfaces default, I didn't change any settings.

**Comment by WellingGuzman** [comment] 2018-12-28 14:08
This is an expected behavior, I don't know what was the process in the app, but there's only one two user types and those are `user_created` and `user_updated`. You create an integer field with an `user` interface.

You need to create a relationship for the `user` field to `directus_users`.

I will close this ticket as this is not a bug with the API. The fields was not configured properly.

---
For some odd reason I don't know why I could it fix it without deleting and creating the table again. That's another thing for another day.

**Closed** 2018-12-28 14:08 UTC
Labels: duplicate
