### ISSUE TITLE
serverInfo request fails on nginx

### ISSUE THREAD

**Issue by benydc** [directus/api#797] opened 2019-02-27 22:05 UTC
# Bug Report

## Steps to Reproduce

1. Clone directus api from master
2. Use nginx with php-fpm server to serve the data
3. Use Directus Web with api served by nginx
4. Login to Directus Web and check browser logs for CORS and 405 Not Allowed request in Network

## Expected Behavior

Retrieve server info succesfully when making the request to endpoint `/` using nginx

## Actual Behavior

Cannot retrieve server info when it's making a OPTIONS & GET request to the nginx server to endpoint `/`

## Other Context & Screenshots

This works for all other http servers like Apache, Caddy or local php server.

Nginx Default conf
https://gist.github.com/benydc/2e41b05edcddce62b17649b707c2931d

Nginx conf
https://gist.github.com/benydc/69de3c6d4249551c2ae40fae5a1dcd7e

Screenshots
<img width="1677" alt="screenshot 2019-02-27 at 22 23 23" src="https://user-images.githubusercontent.com/19665791/53526264-5f797900-3aec-11e9-875e-3d7785313182.png">
<img width="835" alt="screenshot 2019-02-27 at 11 45 04" src="https://user-images.githubusercontent.com/19665791/53526286-7029ef00-3aec-11e9-9fbf-afe284100c28.png">
<img width="1580" alt="screenshot 2019-02-27 at 10 17 40" src="https://user-images.githubusercontent.com/19665791/53526295-791ac080-3aec-11e9-8646-c1f87e2641aa.png">

## Technical Details

- Device: [Desktop, Docker]
- OS: [MacOS 10.14.2, Alpine]
- Web Server: [Nginx 1.15.8]
- PHP Version: [7.3.2]
- Database: [MySQL 8.0.15]
- Install Method: [cloned `master` branch]

**Comment by hemratna** [comment] 2019-07-09 07:14
Hi @benydc 
I am not able to reproduce the issue on my nginx setup. https://gist.github.com/hemratna/1c782a8128943eb0404a088adf257677
(*I replace some server secret with {_var_}*)

In my end, it is working fine.

I am suggesting, Please take the latest version of App and Api and try once again.

**Comment by benhaynes** [comment] 2019-07-09 13:38
Hey @benydc — let us know if things are working for you with the most recent versions of Directus. Since we can not reproduce this issue and because it's technically on an "alternate stack" (we only officially support Apache), I will close this for now. If we get some updates saying this is still not working we can re-address.

**Closed by benhaynes** 2019-07-09 13:38 UTC
Labels: alt stack, bug

**Comment by cesasol** [comment] 2019-07-11 17:58
I found a solution for nginx, just enable cors for the root only, here is the snippet to do so.

```
# This should be before any other location to allow overrides down the line.
location = / { # Don't foget the equal sign
	if ($request_method = 'OPTIONS') {
		# The needed domains
		add_header 'Access-Control-Allow-Origin' '*';

		# The same methods that are across directus, maybe GET is enough for this route
		add_header 'Access-Control-Allow-Methods' 'GET,POST,PUT,PATCH,DELETE,HEAD';

		# The same headers that are present on other requests
		add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization';
		# I took the liberty to increment the max age of the preflight to a 20 days
		add_header 'Access-Control-Max-Age' 1728000;
		# Could work without this one
		add_header 'Content-Type' 'text/plain; charset=utf-8';
		# Is necesary since is an OPTIONS requests
		add_header 'Content-Length' 0;
		# Return here, there is no need to pass it to php
		return 204;
	}

	# Cover the same request types from above with the same block
	if ($request_method ~* '(GET|POST|PUT|PATCH|DELETE|HEAD)') {
		# Again your whitelisted domains if any
		add_header 'Access-Control-Allow-Origin' '*';
		add_header 'Access-Control-Allow-Methods' 'GET,POST,PUT,PATCH,DELETE,HEAD';
		add_header 'Access-Control-Allow-Headers' 'Content-Type,Authorization';
		# It worked without exposing more headers.
		# add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
	}
}
```

**Comment by benhaynes** [comment] 2019-07-11 19:29
@directus/api-team — is this something we should add to the Codebase or Docs?

**Comment by rijkvanzanten** [comment] 2019-07-11 20:54
I think we should add the CORS headers on the server/ endpoints by default, instead of relying on the webservers to add that.

@benhaynes generally speaking, lets try to keep environment specific config files out of the repo

**Comment by bjgajjar** [comment] 2019-07-12 13:04
@rijkvanzanten 

We have it already :) 

![image](https://user-images.githubusercontent.com/19200178/61130122-949eca80-a4d3-11e9-9e3f-6b0097948f90.png)

**Comment by hemratna** [comment] 2019-07-12 13:06
@benhaynes For the list out all the server config, Can we create a seprate repo and link it with documentation?

**Comment by benhaynes** [comment] 2019-07-12 14:13
Absolutely! This seems like the best way to me... I'll let @rijkvanzanten create it/them so he can come up with the repo name. 😄 

I thought we had this in the past... maybe we deleted them?? 🤔

**Comment by rijkvanzanten** [comment] 2019-07-12 14:35
@bjgajjar That means that @cesasol shouldn't have to rely on a special config to enable it. @cesasol are you using the latest version of the API?

**Comment by cesasol** [comment] 2019-07-12 15:38
Yes I am, just updated yesterday

**Comment by rijkvanzanten** [comment] 2019-07-12 15:40
@cesasol and you didn't have the CORS headers in `/` without having to update the nginx config?

**Comment by cesasol** [comment] 2019-07-15 22:49
I didn't, that's why I stumbled into this issue in the first place.
