### ISSUE TITLE
8.4 broke existing Migrations

### ISSUE THREAD

**Issue by nicam** [directus/api#1657] opened 2020-01-15 16:56 UTC
In the 8.4 Release the Constant

_\Directus\Database\Schema\DataTypes::TYPE_USER_CREATED_

got replaced by

_\Directus\Database\Schema\DataTypes::TYPE_OWNER_

The following files still use the old Constant:
 20191123053252_update_directus_files_field.php https://github.com/directus/api/blob/master/migrations/upgrades/20191123053252_update_directus_files_field.php

20191202164209_reset_directus_fields.php
https://github.com/directus/api/blob/master/migrations/upgrades/20191202164209_reset_directus_fields.php

This causes the migrations to break.

**Comment by nashtu3000** [comment] 2020-01-16 11:27
I can confirm this as well. My directus install is currently broken after an upgrade to the latest version. I tried upgrading from 7.10.0.

I followed the guide from the release notes but I am getting this error in the log when accesing the login page.

**Comment by nicam** [comment] 2020-01-16 11:51
Great :)

**Comment by bjgajjar** [comment] 2020-01-16 16:53
Duplicate of #1652
Fixed in #1653

**Closed by bjgajjar** 2020-01-16 16:53 UTC
Labels: bug
