### ISSUE TITLE
Server Error After Upgrade

### ISSUE THREAD

**Issue by cristianopolicarpo** [directus/api#869] opened 2019-03-26 13:30 UTC
# Bug Report

## Steps to Reproduce

1. After login in admin:
2:Error
Server Error
Something is wrong with this instance’s server or database.

## Technical Details

- Device: Desktop
- OS: linux CentOS release 6.10
- PHP Version: PHP 7.2.14
- Database: MySQL Ver 14.14 Distrib 5.5.42
- Install Method: cloned `master` branch

**Comment by bjgajjar** [comment] 2019-05-23 07:23
Hey @cristianopolicarpo 

Just clone the repo of v7.0.19; But not able to replicate this issue. Can you upgrade it with the latest one and try again?

**Comment by cristianopolicarpo** [comment] 2019-05-23 12:29
> Hey @cristianopolicarpo
> 
> Just clone the repo of v7.0.19; But not able to replicate this issue. Can you upgrade it with the latest one and try again?

Yes of course. I'll do this and I'll let you know.

**Comment by cristianopolicarpo** [comment] 2019-05-23 13:42
> Hey @cristianopolicarpo
> 
> Just clone the repo of v7.0.19; But not able to replicate this issue. Can you upgrade it with the latest one and try again?

I made a new installation cloning Directus Master is the error continues. (Server Error
Something is wrong with this instance's server or database.)

When I run: git checkout tags/v7.0.19 it works perfectly. 

So I guess this must be related to some change that happened in Directus Suite version 190325A (which is the later v7.0.19 version)

Remembering that the error occurs on two different servers. One with CentOS 6 and the other with CentOS 7. This second server is fresh, which I set up only to test Directus and check if it was a problem from my old server, but the error remains on both servers.

It would be great to know if someone is running the current version of Directus Suite on CentOS.

Below is the log file generated after the installation I did recently.
[error.2019-05-23.log.txt](https://github.com/directus/api/files/3212387/error.2019-05-23.log.txt)

**Comment by shealavington** [comment] 2019-05-24 09:20
I wonder if it's an issue related to #2224, where the authorization is failing to be provided correctly?

**Comment by bjgajjar** [comment] 2019-05-30 10:49
@cristianopolicarpo Confirmed that this is the issue regarding CentOS! Will check this is CentOS and provide the update!

**Comment by cristianopolicarpo** [comment] 2019-05-30 14:03
> @cristianopolicarpo Confirmed that this is the issue regarding CentOS! Will check this is CentOS and provide the update!

Ok, thanks!

**Comment by hemratna** [comment] 2019-07-18 06:39
We are not able to reproduce. Please take the latest pull and let me know.
I am closing this issue. Feel free to open the issue.

**Closed by hemratna** 2019-07-18 06:39 UTC
Labels: alt stack, bug, not reproducible

**Comment by CaioCosta** [comment] 2019-08-16 17:56
Sorry for commenting on a closed issue, but this is also happening with me. Same thing: fresh install from the HEAD and I can't log in (Server Error Something is wrong with this instance’s server or database.). I'm on MacOs 10.13.6, running PHP 7.2.20 and MySQL 5.7.6.

Console output:

```
Navigated to http://directus.test/admin/
GET http://directus.test/interfaces 401 (Unauthorized)
{__ob__: Ie}
GET http://directus.test/_/collections 403 (Forbidden)
GET http://directus.test/_/users/me?fields%5B0%5D=id&fields%5B1%5D=avatar.%2A&fields%5B2%5D=email&fields%5B3%5D=first_name&fields%5B4%5D=last_name&fields%5B5%5D=locale&fields%5B6%5D=roles.%2A.%2A 404 (Not Found)
GET http://directus.test/_/settings 403 (Forbidden)
GET http://directus.test/layouts 401 (Unauthorized)
GET http://directus.test/pages 401 (Unauthorized)
GET http://directus.test/_/collection_presets?filter%5Btitle%5D%5Bnnull%5D=1&filter%5Buser%5D%5Beq%5D=1 403 (Forbidden)
GET http://directus.test/_/collection_presets?filter%5Btitle%5D%5Bnnull%5D=1&filter%5Buser%5D%5Bnull%5D=1 403 (Forbidden)
GET http://directus.test/_/users?fields%5B0%5D=id&fields%5B1%5D=first_name&fields%5B2%5D=last_name&fields%5B3%5D=title&fields%5B4%5D=status&fields%5B5%5D=timezone&fields%5B6%5D=roles.%2A&fields%5B7%5D=avatar.%2A&fields%5B8%5D=company 403 (Forbidden)
GET http://directus.test/ 401 (Unauthorized)
Uncaught (in promise) {code: 3, message: "Unauthorized request"}
GET http://directus.test/_/relations?limit=-1 403 (Forbidden)
```

As far as I managed to debug, it looks like the method `getRolesId()` in Acl.php is returning an empty array. That makes the method `isAdmin()` return false and I guess that's the reason why I can't login.

The table `directus_user_roles` has only one row, with `1` in all three fields.

The table `directus_permissions` has no rows.

**Comment by benhaynes** [comment] 2019-08-16 21:41
Hmm, any thoughts @directus/api-team ?

**Comment by CaioCosta** [comment] 2019-08-19 00:36
By the way, I just found out that the same thing is happening to the Nightly Demo.

**Comment by rijkvanzanten** [comment] 2019-08-21 19:51
@CaioCosta I don't see this issue on the live demo. Maybe someone screwed with the permissions when you checked?

**Comment by CaioCosta** [comment] 2019-08-22 01:48
@rijkvanzanten @benhaynes I can't see the issue in the live demo anymore. After a lot of fiddling and debugging I just found out that the issue is caused by my setup. I'm using "CGI mode" on MAMP, which is stripping the Autorization Header — and from there nothing works. Sorry again for raising this issue.

**Comment by hemratna** [comment] 2019-08-22 06:43
Hi, @CaioCosta Thanks a lot for looking into this.
We are maintaining a repo for making a note for such an edge case. 
I added your use case in https://github.com/directus/server-configs/blob/master/MAMP/README.md

Please verify. I am also requesting please provide the setup for MAMP. So I can update the docs.
