### ISSUE TITLE
Failed generating the SQL query.

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1228] opened 2019-08-29 10:24 UTC
## Bug

`artist` one-to-many with `artworks` one-to-many with `images`

`images` collection contains file field

* When updating images file from artist, error occur.

## Steps to Reproduce

Everything is in  [Screenrecording](https://drive.google.com/file/d/1t9_b1BafWAc-COT_x9od5MhvJj1eDU3H/view?usp=sharing) using directus demo

## Expected Behavior

```
message: "Failed generating the SQL query."
query: "INSERT INTO `directus_users` (`id`, `external_id`) VALUES (NULL, '6dd89760-7169-486d-9dab-431827fd384e')"
```

## Actual Behavior

It should save successfully

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: v2.5.0 build
- Directus App: 7.10.0

**Comment by bjgajjar** [comment] 2019-09-05 09:28
@rijkvanzanten - I think this is the time when we should pass only updated fields as a payload in O2M and M2M.

Here, `created_by` is also passing along with the `file` id for updation and that's the cause of this issue.

**Comment by rijkvanzanten** [comment] 2019-09-05 20:54
What happened there, I'm pretty sure we fixed the O2M diffing already 🤔 Maybe that wasn't released yet?

**Comment by bjgajjar** [comment] 2019-09-06 04:55
> I'm pretty sure we fixed the O2M diffing already

Maybe. As right now it is passing whole object instead of updated data.

**Comment by bjgajjar** [comment] 2019-09-10 05:23
Closing this as we should ass only updated fields as a payload in O2M and M2M which is duplicate of  https://github.com/directus/app/issues/2042

**Closed by bjgajjar** 2019-09-10 05:23 UTC
Labels: bug

**Comment by JbalTero** [comment] 2019-09-10 05:29
Ok they related thanks @bjgajjar
