### ISSUE TITLE
New permission level?

### ISSUE THREAD

**Issue by andgar2010** [directus/api#1679] opened 2020-01-21 21:59 UTC
• Version of Directus
8.4.0

• PHP version
7.2.24

• MySQL version
mysqld Ver 5.7.28

• Webserver + version
apache 2.4.29

I researched the documentation, but did not find [Permissions new level](https://docs.directus.io/guides/permissions.html#collection-level).

I don't know how to express it. I tried some translation tools, but I wasn't satisfied.
I will describe it and see if you can understand it:

Client wants to manage the permissions to assign a user or several users (any role that items in a collection by created user ) to be able to read or modify in a collection item. Because Directus only has to manage items in mine only (Created by or modified by) or Role only (Created by or modified by)

![image](https://user-images.githubusercontent.com/19521054/72846802-4bdc8100-3c6f-11ea-99c2-4b1f7d12b535.png)

**Comment by benhaynes** [comment] 2020-01-22 12:08
Hey @andgar2010 — I'm not sure I completely understand this new permission level. It sounds like our "Role Only" would work... but maybe I'm misunderstanding.

Could you use an example to describe what you're looking for?

**Comment by andgar2010** [comment] 2020-01-23 15:32
Hi @benhaynes 
Give a example of User history: 
A collection is composed of 3 actors which are: client, coordinator and agent (the coordinator and the agent being related to a place).

The client can create a request (new item in the collection with data: place id, date created in and created by client) and read by its created. 

The coordinator can read only the assigned place and change the request only to assign or change the agent. 

The agent can read and modify the service only when the coordinator has assigned a request to it.

**Comment by benhaynes** [comment] 2020-01-23 16:40
Ahh, this is a very complex edge-case then. You still might be able to accomplish this with the "My Role Only" permission and setting the "owner" through event hooks, or maybe even with custom interfaces.

Still, I'll close this as a duplicate of our more robust permission system that will likely be included in the Laravel API port we're working on now: https://github.com/directus/api/issues/511

**Closed by benhaynes** 2020-01-23 16:40 UTC
Labels: needs more info, question

**Comment by andgar2010** [comment] 2020-01-24 21:39
Let's talk about this topic, but can permissions be granted for fields (CRUDE)?

**Comment by benhaynes** [comment] 2020-01-24 22:03
Yes, you can toggle field READ/WRITE access (and you can do so per status):

https://docs.directus.io/guides/permissions.html#field-level
