### ISSUE TITLE
Required status field is saved even though it is empty but data not displayed

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1172] opened 2019-08-02 10:32 UTC
# Bug Report

## Steps to Reproduce

* Fresh install of v2.3.1
* Create `status_test` collection without the `status` field
* Create `status` field using the `status` field type and make it required.
* Add an item.

Here's [screen recording](https://drive.google.com/file/d/15ZbkDsAPmRN8yX7guHS_WnTsHdKTDN57/view?usp=sharing)

## Expected Behavior

* There should be an error saying that Status field is required.

## Actual Behavior

* It says Item saved. BUT it is not displayed in the list of items for that collection.

## Other Context & Screenshots

The item is actually saved in the database but the `status` value in db is `raf`.

![image](https://user-images.githubusercontent.com/3615746/62364205-80d70900-b553-11e9-9c76-67426bf44ad2.png)

Here's the field structure:

```json
{
  "type": "status",
  "datatype": "VARCHAR",
  "length": 20,
  "field": "status",
  "interface": "status",
  "default_value": "draft",
  "width": "full",
  "options": {
    "status_mapping": {
      "published": {
        "name": "Published",
        "value": "published",
        "text_color": "white",
        "background_color": "accent",
        "browse_subdued": false,
        "browse_badge": true,
        "soft_delete": false,
        "published": true
      },
      "draft": {
        "name": "Draft",
        "value": "draft",
        "text_color": "white",
        "background_color": "blue-grey-100",
        "browse_subdued": true,
        "browse_badge": true,
        "soft_delete": false,
        "published": false
      },
      "deleted": {
        "name": "Deleted",
        "value": "deleted",
        "text_color": "white",
        "background_color": "red",
        "browse_subdued": true,
        "browse_badge": true,
        "soft_delete": true,
        "published": false
      }
    }
  },
  "required": true
}
```

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.1.40
- Install Method: v2.3.1 build

**Comment by bjgajjar** [comment] 2019-08-06 13:46
Hey @JbalTero 

Not able to replicate this. @rijkvanzanten can you please verify this once?

**Comment by JbalTero** [comment] 2019-08-08 04:51
@bjgajjar  @rijkvanzanten I'm upgraded now to Spouting Whale — (190807A)

Still the same issue, here a [screenrecording](https://drive.google.com/file/d/1Io0BQkpmXkruWY_98n70Yxi7PQf_TMHD/view?usp=sharing) of  what happens when I add `status` field manually.

**Comment by bjgajjar** [comment] 2019-08-08 10:55
@JbalTero —  I am not able to reproduce this neither in my local nor in the [latest release](https://directus.app/).

Don't know the exact reason, why you are getting this issue at your end! Maybe @rijkvanzanten can help you here.

**Comment by JbalTero** [comment] 2019-08-08 11:21
@bjgajjar I was also able to reproduce this in my remote test server.

**Comment by benhaynes** [comment] 2019-08-08 11:43
Hey @JbalTero — did you try replicating on the Directus demo? That might be useful since it's a shared system. Otherwise, could you send us a database dump to help debug?

**Comment by JbalTero** [comment] 2019-08-08 13:12
@benhaynes it works fine in the Directus Demo, are you using MariaDb in that?

**Comment by benhaynes** [comment] 2019-08-08 13:15
MySQL I believe.

**Comment by JbalTero** [comment] 2019-08-08 13:18
@benhaynes @bjgajjar @rijkvanzanten 

I think this isssue is specific in MariaDb, Check my [recording](https://drive.google.com/file/d/1ulcAlG7rkVkQ1npEFbBBPjzZh-X1kut7/view?usp=sharing).

The field's default value is getting trimmed in its first and last character.

**Comment by benhaynes** [comment] 2019-08-08 13:25
Ugh, this issue has come up before. We need to solve this "trims first/last character" issue once and for all. At least now we know it's likely a MariaDB specific problem.

🔔 @directus/api-team

**Comment by JbalTero** [comment] 2019-08-08 13:32
This issue is gone if you create a collection with `status` field pre-selected.

**Comment by bjgajjar** [comment] 2019-08-09 05:10
@JbalTero 

I checked this in `MariaDB` but still not able to replicate over there :(

**Comment by JbalTero** [comment] 2019-08-09 07:34
@bjgajjar Using MariaDB, did it go inside `src/core/Directus/Database/Schema/SchemaManager.php:672`?

**Comment by bjgajjar** [comment] 2019-08-09 08:42
Yes

**Comment by JbalTero** [comment] 2019-08-09 09:48
@bjgajjar @benhaynes 

This issue occurs in Mariadb 10.1, but not on Mariadb 10.2+

It is because the column_default in 10.1 is not quoted, while starting 10.2, column_default is quoted.

[Changes & Improvements in MariaDB 10.2](https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-102/)

![image](https://user-images.githubusercontent.com/3615746/62770477-b472df80-bacd-11e9-8492-4e3c952cc28f.png)

That's the reason @bjgajjar was not able to replicate on her side since she is using 10.2, while I'm using 10.1

**Comment by bjgajjar** [comment] 2019-08-09 12:08
Closing this as it is not `Directus` related.

**Closed by bjgajjar** 2019-08-09 12:08 UTC
Labels: bug

**Comment by benhaynes** [comment] 2019-08-09 12:27
Let's plan on adding a minimum MariaDB version to the docs. If someone wants to submit a PR to fix this we'll review.

**Comment by benhaynes** [comment] 2019-08-09 13:32
Thanks @shealavington 

https://github.com/directus/docs/commit/7b1404a448a8ab3f8b79f01ef59cd52f2bc829d4
