### ISSUE TITLE
Thumbnails API Environment Configuration Not Found

### ISSUE THREAD

**Issue by fecou** [directus/api#577] opened 2018-11-08 08:28 UTC
# Bug Report

## Steps to Reproduce

1. Go to 'https://api....com/uploads/_/originals/Chrysanthemum.jpg'
2. Ok, the full image is returned
3. Go to 'https://api....com/uploads/_/thumbnails/200/200/crop/good/Chrysanthemum.jpg'
4. Get Json error 8 ; "API Environment Configuration Not Found: uploads"
5. Vi config/api.php and try to change 
6. Try to change :  'thumb_root' => 'public/uploads/_/thumbnails',
    to  'thumb_root' => 'https://api....com/uploads/_/thumbnails', 
    (note: my subdomain is pointing to public directory and I have 'root' => 'uploads/_/originals' and 'root_url' => '/uploads/_/originals')
7. Still get same error when going to 'https://api....com/uploads/_/thumbnails/200/200/crop/good/Chrysanthemum.jpg'

## Expected Behavior
Get the thumnail of the image 200*200 pixels...

## Actual Behavior
Get json error

## Other Context & Screenshots

Mutualized server 1and 1...
I tryed to add thumbnails settings in database like in issue https://github.com/directus/api/issues/469, but it doesn't change
Note: Also when I insert an image in my files, thumbnails throw error (404 not found in console)

## Technical Details

- Device: [eg: Firefox]
- OS: [eg: Linux]
- Web Server: [eg: Apache or nginx ?]
- PHP Version: [eg: 7.1.0]
- Database: [eg: MySQL 5.6]
- Install Method: [eg: cloned `master` branch from api 2.0.2  and app 7.0.2 separately]

**Comment by AntiCZ** [comment] 2018-11-19 16:14
Hello, check src\web.php line 28.

Problem is that Directus try to find a project with name "upload"

https://api....com/uploads/_/originals/Jellyfish-1.jp - ok

but change
  https://api....com/uploads/_/thumbnails/200/200/crop/good/Chrysanthemum.jpg  
  to
  https://api....com/thumbnail/_/200/200/crop/good/Chrysanthemum.jpg

**Comment by WellingGuzman** [comment] 2018-11-21 14:36
Hey @fecou, where this url returned by the API? the thumbnailer url format is different. You can take a look at the url format here: https://github.com/directus/docs/blob/master/api/admin/thumbnailer.md#url-syntax

**Comment by fecou** [comment] 2018-11-22 09:22
Hello,
Thank you for your answers. I understand what yo mean.
But it still doesnt work with https://api....com/thumbnail/_/200/200/crop/good/Chrysanthemum.jpg 
If, as @benhaynes said, I go to files I see a 404 error on the loading of my images. So it's not about the url I use. It might be a misconfiguration, if I am the only one to face this issue...

**Comment by stickgrinder** [comment] 2018-11-22 13:46
I'm facing a similar issue (if not the very same). Thumbnails are nowhere to be found in the app interface and I'm not sure how to query the API directly so I can have an idea of what's going on.

**Comment by stickgrinder** [comment] 2018-11-22 14:02
OK, my problem may be that dockerized version of Directus is running with nginx, thus bypassing the .htaccess altogether (I'm referring to to the page linked by @WellingGuzman above)

**Comment by stickgrinder** [comment] 2018-11-22 15:03
Further investigation led me to this.

Request: `GET `
Response: `404` with the following JSON body:

```
{
  "error" : {
    "error" : 8,
    "message" : "API Environment Configuration Not Found: thumbnail"
  }
}
```
It seems the PHP script is invoked correctly but something similar to the main issue happens, only at a different level.

**Comment by WellingGuzman** [comment] 2018-11-23 14:03
@stickgrinder that's the issue here, we need to create a new location block to catch the `/thumbnail` request.

Try something like this in your api nginx config:

```
location /thumbnail {
    rewrite /thumbnail/(.*) /thumbnail/index.php last;
}
```

Let me know if that works for you.

**Comment by stickgrinder** [comment] 2018-11-23 16:13
I tried that stuff but as I said on slack, I'm not an nginx ninja and I made a mistake, it seams!
I'm going to test it out, thanks!

**Comment by stickgrinder** [comment] 2018-11-23 18:11
I tried that stuff but as I said on slack, I'm not an nginx ninja and I made a mistake, it seams!
I'm going to test it out, thanks!

**Comment by stickgrinder** [comment] 2018-11-23 18:12
Actually it doesn't seem to work... I'll try to understand which kind of call the File Library is making to retrieve images since the console is not helping me at all.

**Comment by WellingGuzman** [comment] 2018-11-23 18:17
@stickgrinder how does your nginx configuration looks like? it seems that the problem is actually the missing location in your nginx configuration. it should be almost the same as your `/` location block, but with `/thumbnail` in the front.

**Comment by joshuaavalon** [comment] 2018-11-28 02:41
I have the same problem if I run the [Docker version](https://github.com/directus/docker/blob/e586fe0f124612deccf4176d3ca6e2b012ed94b5/examples/single-api/docker-compose.yml) on a fresh install.

**Comment by stickgrinder** [comment] 2018-12-06 08:04
@WellingGuzman I decided to file my progress on the thumbnail problem with nginx where it belongs (directus/docker): https://github.com/directus/docker/issues/10#issuecomment-444782346, just in case you feel like following up the discussion.

Thanks a lot!

**Comment by rjwismar** [comment] 2018-12-21 10:02
I have also a problem with that.
I figure out that '$this->getConfig()' will return a array with the needed entry 'thumbnail_demensions' but the 'ArrayUtils' can't get them. The 'ArrayUtils' return NULL but not the configured settings.
```
/**
     * Return supported thumbnail file dimesions
     *
     * @return array
     */
    public function getSupportedThumbnailDimensions()
    {
        $defaultDimension = '200x200';

        // returns NULL
        $dimensions =  $this->parseCSV(
             ArrayUtils::get($this->getConfig(), 'thumbnail_dimensions')
        );
        
        if (!in_array($defaultDimension, $dimensions)) {
            array_unshift($dimensions, $defaultDimension);
        }
        
        return $dimensions;
    }
```

In this example I get the integer key of 'thumbnail_demensions' and in the next step I get the value of this key

```
/**
     * Return supported thumbnail file dimesions
     *
     * @return array
     */
    public function getSupportedThumbnailDimensions()
    {
        $defaultDimension = '200x200';

        $key = array_search('thumbnail_dimensions', array_column($this->getConfig(), 'key'));

        $dimensions =  $this->parseCSV(
            $this->getConfig()[$key]['value']
        );
        
        if (!in_array($defaultDimension, $dimensions)) {
            array_unshift($dimensions, $defaultDimension);
        }
        
        return $dimensions;
    }
```

So I think the ArrayUtils didn't work correctly or the '$this->getConfig()' will return an incorrect array.

**Comment by WellingGuzman** [comment] 2018-12-21 23:12
Hey @rjwismar, there was a bug in the `get_directus_thumbnail_settings` (https://github.com/directus/api/blob/master/public/thumbnail/index.php#L26) function that return the the settings as a numeric index list, instead of a key-value array.

It was fixed by https://github.com/directus/api/commit/288503e7c4892e349e9798d657e0cba49b5e265d

**Comment by WellingGuzman** [comment] 2019-01-04 18:59
This was fixed by https://github.com/directus/api/commit/288503e7c4892e349e9798d657e0cba49b5e265d. Due to inactivity I believe this confirm the fix, and I am closing this ticket.

if there's problem with the thumbnailer getting 404, please let me know and I will reopen this ticket.

**Closed by WellingGuzman** 2019-01-04 18:59 UTC
Labels: documentation
