### ISSUE TITLE
directus suite 7.0.9 on shared hosting issues

### ISSUE THREAD

**Issue by CodexAnima** [directus/api#646] opened 2018-12-01 13:06 UTC
Hello everyone!

To begin with, if you tried to install directus suite 7.0.9 on a shared hosting without ssh console and without access to server configurations and the admin-login gives that nasty "couldn't reach api", this did it for me:

My domain to the app is:
`https://domain.tld/subfolder/apifolder/public/admin`

- set write permissions with ftp programm on `/logs/`, `/public/uploads/`, `/public/uploads/_/`, `/public/uploads/_/originals`, `/public/uploads/_/thumbnails`

- edit the `/public/htaccess` file and use absolute paths in the rewriterule.
=> `RewriteRule ^admin/(.*)  /subfolder/apifolder/public/admin/index.html`
=> `RewriteRule !^admin /subfolder/apifolder/public/index.php?%{QUERY_STRING} [L]`

## Version Info
  - Directus Suite 7.0.9
  - PHP version 7.2.12 (shared hosting)
  - MySQL version 5.6.14? (shared hosting)
  - Web server: Linux/Apache (shared hosting)

## Expected Behavior
a) query api with token request returns token
b) change logo in global settings
c) thumbnails showing in user profile/file system
d) WYSIWYG editor with the ability to modify html-code (like directus 6)
e) use folders in file system to organize content

## Actual Behavior
a) failing credential password verification (php curl server/ping returns pong)
b) no logo change in global settings due to "Error 213, Attempting to write an array as the value for field "value" in "directus_settings" (known issue) #2252
c) no thumbnails found (`https://domain.tld/subfolder/apifolder/public/thumbnail/_/200...` = 404 not found)
d) WYSIWYG has no option to edit html-code (insert classes, spans, data-attributes, ...)
e) no option to create/choose folder if uploading image/file

## Steps to Reproduce
a)
- PHP curl `https://domain.tld/subfolder/apifolder/public/_/auth/authenticate` with post credentials
- Returns 404 not found
- Further investiagion reveals password verification fails
- get passwordhash from database with pdo and try php `password_verify()`. Failed!
- hashing my password with `password_hash()` and `password_verify()` succeeded!
= There might be an error with your user password storing?

b)
- Field "value" in the database is of datatype "`TEXT`"

c)
- I don't know where to check
- there is no whitelist option for thumbnails in the global settings
- settings in api.php for 'storage':
```
 'adapter' => 'local',
  'root' => 'public/uploads/_/originals',
  'root_url' => '/uploads/_/originals',
  'thumb_root' => 'public/uploads/_/thumbnails',
```

d)
- choose "WYSIWYG" or "Advanced WYSIWYG" as datatype
- no option for html-code editing available
= quill editor do not have this feature, but directus 6 editor did

e)
- upload image. you can edit title, tags, location, description and metadata. no folder input/edit field.

Keep on rocking!

**Comment by WellingGuzman** [comment] 2018-12-10 21:40
This probably is related with your hosting (dependencies).

> a) failing credential password verification (php curl server/ping returns pong)
> b) no logo change in global settings due to "Error 213, Attempting to write an array as the value for field "value" in "directus_settings" (known issue) #2252

The problem is not rewriting. How are you able to login when login is failing?

> c) no thumbnails found (https://domain.tld/subfolder/apifolder/public/thumbnail/_/200... = 404 not found)

Can you explain how your directory structure is set in your hosting for Directus API?

> d) WYSIWYG has no option to edit html-code (insert classes, spans, data-attributes, ...)
> e) no option to create/choose folder if uploading image/file

@rijkvanzanten could help you here.

---

Are you using php 5? The build version is compiled with php 7, and some packages are incompatible with php 5.

**Comment by CodexAnima** [comment] 2018-12-12 12:48
> This probably is related with your hosting (dependencies).
> 
> > a) failing credential password verification (php curl server/ping returns pong)
> > b) no logo change in global settings due to "Error 213, Attempting to write an array as the value for field "value" in "directus_settings" (known issue) #2252
> 
> The problem is not rewriting. How are you able to login when login is failing?

for a):
I can login directly at `https://domain.tld/subfolder/apifolder/public/admin/login` and work inside the app.

However if I try to query with php curl post to `https://domain.tld/subfolder/apifolder/public/_/auth/authenticate` (with mail and pwd, same as I would enter at admin login) from another domain (`https://domain2.tld/web/index.php`) to the authentication failes.

If I query the stored passwordhash from directus user datatable with php pdo in utf-8 encoding and compare it with my password, the result is false. If I hash my password and check it again with my password, the result is true.

> 
> > c) no thumbnails found (https://domain.tld/subfolder/apifolder/public/thumbnail/_/200... = 404 not found)
> 
> Can you explain how your directory structure is set in your hosting for Directus API?

`https://domain.tld/subfolder/apifolder`
`/bin`
`/config`
`/docker`
`/logs`
`/migrations`
`/public`
`== /admin`
`== /extensions`
`== /thumbnail`
`== /uploads`
`== .htaccess < changed (see above "Version Info" at topside)` 
`== index.php`
`/src`
`/vendor`

> 
> > d) WYSIWYG has no option to edit html-code (insert classes, spans, data-attributes, ...)
> > e) no option to create/choose folder if uploading image/file
> 
> @rijkvanzanten could help you here.

I will wait for his reply :)

> 
> Are you using php 5? The build version is compiled with php 7, and some packages are incompatible with php 5.

I am using php 7.2.12, latest stable (see "Version Info" at topside for more info)

I attached my latest error log: [error.2018-12-06.log](https://github.com/directus/api/files/2671892/error.2018-12-06.log)

**Comment by WellingGuzman** [comment] 2018-12-12 13:21
> a) failing credential password verification (php curl server/ping returns pong)

I would like to see some example of the curl command you are using, what errors throws and what errors are logged in your `logs` directory.

> b) no logo change in global settings due to "Error 213, Attempting to write an array as the value for field "value" in "directus_settings" (known issue) #2252

As this is a known bug, let's keep this out of this ticket for the sake of simplicity so we can solve the problem using curl.

What I understand besides the `b)` issue, the other issue with the API is not being able to execute some curl command to some endpoint without getting error. Let me know what's the error you are getting when you run authentication with curl, so we can understand better your situation.

**Comment by WellingGuzman** [comment] 2018-12-12 14:46
This doesn't seem to be an issue with the API, but it seems to be an issue using the correct api endpoint (url).

In the developer tools network take a look at the url the application uses and see what's the full url.

I tried your example and the only problem I saw was that the endpoint in this function `comm( $url . '/_/auth' )` doesn't exists. There's no `/_/auth` endpoint, the rest worked as expected.

If the problem doesn't exists with the application, and does when you use this script you are building there's a high chance the URLs are incorrect.

**Comment by CodexAnima** [comment] 2018-12-14 10:20
> This doesn't seem to be an issue with the API, but it seems to be an issue using the correct api endpoint (url).
> 
> In the developer tools network take a look at the url the application uses and see what's the full url.
> 
> I tried your example and the only problem I saw was that the endpoint in this function `comm( $url . '/_/auth' )` doesn't exists. There's no `/_/auth` endpoint, the rest worked as expected.
> 
> If the problem doesn't exists with the application, and does when you use this script you are building there's a high chance the URLs are incorrect.

I am away from my computer for a some days due to reaching the years end. I'll be back when I got some news to this.

**Comment by CodexAnima** [comment] 2019-01-02 13:57
Happy New Year! 

For **a)** , I did it the wrong way. I did not need administrative access.
I won't create data outside the app and just need public access from PHP curl to load items into webpages. (Did set public rights to read from the requested collections). That is functional, so part a) can be closed hereby.

Now that I updated to version **7.0.13**, there are still running open issues:

c) no thumbnails found or generated in user profile and file system - **pending**
=> System searches for `https://domain.tld/subfolder/apifolder/public/thumbnail/_/200/200/crop/good/image.png`

d) for fieldtype "advanced WYSIWYG" there is no option to modify content as html-code (like directus 6 had the ability to insert classes, spans, data-attributes, ...) - **pending**
=> maybe @rijkvanzanten knows something?

e) no option to create/choose a folder for uploaded image or file - **pending**
=> maybe @rijkvanzanten knows something?

You still keep on rocking!

**Comment by rijkvanzanten** [comment] 2019-01-04 15:06
Heya!

d) We're using [Quill](http://quilljs.com) as the editor. I'll check if there's a way to add a "raw HTML" button or something similar.

e) We don't have support for folders yet. Keep an eye on https://github.com/directus/app/issues/228 to track the progress 🙂

**Comment by rijkvanzanten** [comment] 2019-01-04 15:12
d): https://github.com/directus/app/issues/1230

**Comment by benhaynes** [comment] 2019-01-30 14:37
It seems like the remaining issues here are tracked in other tickets. I'll close this one since it's got a LOT going on. If there are other issues that do not have dedicated tickets then let's open them individually.

Thanks @CodexAnima!

**Closed by benhaynes** 2019-01-30 14:37 UTC
Labels: not reproducible
