### ISSUE TITLE
v2.0.23 - Thumbnailer not working - giving 500 error

### ISSUE THREAD

**Issue by yarick2000** [directus/api#945] opened 2019-05-10 18:42 UTC
# Bug Report

## Steps to Reproduce

1. Go to App and open File Library - all images without thumbnails
4. In browser developer panel you will see that all of them getting 500 error

## Expected Behavior
Thumbnails should be shown

## Actual Behavior
Thumbnails not shown, the default image shown instead

## Other Context & Screenshots

In API error logs there is a following message:
2019/05/10 14:04:41 [error] 1635#1635: *54 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Directus\Filesystem\Thumbnailer::getSupportedFileExtensions() in /mnt/c/Projects/Directus/directus-api/src/core/Directus/Filesystem/Thumbnailer.php:290
Stack trace:
#0 /mnt/c/Projects/Directus/directus-api/src/core/Directus/Filesystem/Thumbnailer.php(255): Directus\Filesystem\Thumbnailer->isSupportedFileExtension('jpg')
#1 /mnt/c/Projects/Directus/directus-api/src/core/Directus/Filesystem/Thumbnailer.php(60): Directus\Filesystem\Thumbnailer->extractThumbnailParams('casino/200/200/...')
#2 /mnt/c/Projects/Directus/directus-api/public/thumbnail/index.php(34): Directus\Filesystem\Thumbnailer->__construct(Object(Directus\Filesystem\Filesystem), Object(Directus\Filesystem\Filesystem), Array, 'casino/200/200/...')
#3 {main}
  thrown in /mnt/c/Projects/Directus/directus-api/src/core/Directus/Filesystem/Thumbnailer.php on line 290" while reading response header from upstream, client: 172.28.5.14, server: api.directus.com, request: "GET /thumbnail/casino/200/200/crop/good/casino-holdem.jpg HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "api.directus.com:8080", referrer: "http://api.directus.com:8080/"

I was going to the code and replaced code of the isSupportedFileExtension function in Thumbnailer class:
    public function isSupportedFileExtension($ext)
    {
        return in_array(strtolower($ext), $this->getSupportedFileExtensions());
    }

 with the following one:

    public function isSupportedFileExtension($ext)
    {
        return in_array(strtolower($ext), Thumbnail::getFormatsSupported());
    }

After that things started to work. So it seems like somehow context of $this was lost, not sure why...

## Technical Details

- Device: PC
- OS: Windows 10.1803
- Web Server: NGINX under WLS
- PHP Version: 7.3.4
- Database: MySQL 8.0.12
- Install Method: cloned `build` branch

**Comment by itsmerhp** [comment] 2019-05-12 17:31
@yarick2000 
function **getSupportedFileExtensions** is defined in same class **Thumbnailer** and it is also returning `Thumbnail::getFormatsSupported()`

So, it is strange that you are getting error Call to undefined method `Directus\Filesystem\Thumbnailer::getSupportedFileExtensions() `

Can you please check that is there any typo error for function **getSupportedFileExtensions()** or is it missing from  **Thumbnailer** class?

**Comment by yarick2000** [comment] 2019-05-13 12:55
I agree that this is strange and yes, there is no typo there.  The same issue was happening to user with name china-xhting in #support Slack channel. Check her post at May 5th at 5:18 pm. She also has NGINX setup.

**Comment by jake-101** [comment] 2019-05-15 19:19
I have this same issue, with Nginx in front of Apache. Original images work and the thumbnails are generated under /uploads/_/thumbnails/200/200/crop/good.

Not sure if it matters or not but I had to turn off `Options +SymLinksIfOwnerMatch` to use Directus.

**Comment by bjgajjar** [comment] 2019-05-17 11:49
Hey @yarick2000  @jake-101 

I checked in `windows` OS  as well as `Nginx` server! But not able to reproduce this. @itsmerhp also reported [here](https://github.com/directus/api/pull/951#issue-278076719) that this issue is not reproducible, So I am closing this issue. Feel free to reopen it. :)

**Closed by bjgajjar** 2019-05-17 11:49 UTC
Labels: alt stack, bug
