### ISSUE TITLE
And or operator causes other filters to break

### ISSUE THREAD

**Issue by kevinvugts** [directus/api#1298] opened 2019-09-10 10:16 UTC
# 🐞 bug report

### Description
I am trying to do some conditional filtering using the and & or operators. Unfortunately after adding one of these operator causes directus to break other requirements / filters.  Below I will attach a code + result json.

## The below code is parsing the correct data from directus with the correct category
```ts
  return client
      .getItems('privileges', {
        fields: ['*', 'image.filename', 'image.data.full_url', 'attachment.*', 'partner.*.*', 'location.*', 'category.*.*', 'type.icon.data.full_url'],
        meta: ['total_count', 'result_count'],
        sort: 'created_on',
        filter: {
          category: {
            'logical': 'and',
            'eq': category
          },
          available_from: {
            'lte': 'now'
          },
          available_until: {
            'gte': 'now'
          }
        },
        limit,
        offset,
      }).then(response => {
        dispatch(getPrivilegesSuccess(key, response))
      }).catch(error => {
        console.log(error);
        dispatch(getPrivilegesFail(key, error))
      });
```

## in contrary the below code response result from directus isn't correct anymore. It is parsing categories with different id's. (also with hardcoding the category id overhere) However the location.city and location.title filter do work as expected. The category filter does not unfortunately. 

```ts
  return client
      .getItems('privileges', {
        fields: ['*', 'image.filename', 'image.data.full_url', 'attachment.*', 'partner.*.*', 'location.*', 'category.*.*', 'type.icon.data.full_url'],
        meta: ['total_count', 'result_count'],
        sort: 'created_on',
        filter: {
          'location.city': {
            'contains': q
          },
          'location.title': {
            'logical': 'or',
            'contains': q
          },
          category: {
            'logical': 'and',
            'eq': category
          },
          available_from: {
            'lte': 'now'
          },
          available_until: {
            'gte': 'now'
          }
        },
        limit,
        offset,
      }).then(response => {
        dispatch(getPrivilegesSuccess(key, response))
      }).catch(error => {
        console.log(error);
        dispatch(getPrivilegesFail(key, error))
      });
```
## 🔥 Exception or Error
No exception or error, just wrong data being returned by directus api. (data with different category.id

## 🌍 Your Environment

"@directus/sdk-js": "^5.3.0",

Any help is much appreciated. Already asked it in the slack group but they forwarded me to create an issue for it.

**Comment by bjgajjar** [comment] 2019-10-03 12:56
> ```ts
> filter: {
>           'location.city': {
>             'contains': q
>           },
>           'location.title': {
>             'logical': 'or',
>             'contains': q
>           },
>           category: {
>             'logical': 'and',
>             'eq': category
>           },
>           available_from: {
>             'lte': 'now'
>           },
>           available_until: {
>             'gte': 'now'
>           }
>         },
> ```

@rijkvanzanten  - On a quick overview, It seems it's related to https://github.com/directus/api/issues/958

**Comment by itsmerhp** [comment] 2019-10-12 18:41
I agree with @bjgajjar, I think this issue is related to the grouping of `AND` and `OR` conditions and it seems to be related to #958, #1067

**Comment by bjgajjar** [comment] 2019-10-15 06:48
Closing this on ref. of https://github.com/directus/api/issues/1067#issuecomment-510546930

**Closed by bjgajjar** 2019-10-15 06:48 UTC
Labels: bug, hacktoberfest

**Comment by kevinvugts** [comment] 2019-10-15 09:15
@bjgajjar Whats's the outcome?

**Comment by bjgajjar** [comment] 2019-10-15 10:37
@kevinvugts - As Rijk mentioned in the https://github.com/directus/api/issues/1067#issuecomment-510546930 -  It's not a bug but a feature that doesn't exist yet. Feel free to open a feature request to discuss possible ways to implement a grouped filter structure.
