### ISSUE TITLE
API pagination doesn't work with parameter page

### ISSUE THREAD

**Issue by konradwww** [directus/api#1404] opened 2019-11-08 09:29 UTC
API pagination doesn't work with GET Parameter `&page=` :
Example Request:
1. `http://localhost:8080/_/items/content?access_token=xxx&fields=*&page=1&limit=10`
2. `http://localhost:8080/_/items/content?access_token=xxx&fields=*&page=2&limit=10` `http://localhost:8080/_/items/content?access_token=xxx&fields=*&page=3&limit=10`
`...` -> delivers the same results as the first one

ℹ️  as workaround I have used GET Parameter `offset` this request delivers correct paginated results.

`http://localhost:8080/_/items/content?access_token=xxx&fields=*&offset=0&limit=10`
`http://localhost:8080/_/items/content?access_token=xxx&fields=*&offset=10&limit=10`
`...`

API Version: 2.6.0
APP Version: 7.11.0

**Comment by bjgajjar** [comment] 2019-11-11 05:41
Hi @konradwww - May I have a dump SQL for your issue? I am not able to reproduce it in local / demo live. It'll be a great help if you can provide the SQL dump. You can provide it in our slack channel too if it's private.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19200178/68563519-d0db3b00-0473-11ea-964b-ee51dcd99ddb.gif)

**Comment by konradwww** [comment] 2019-11-12 13:23
Hello @bjgajjar, for this issue I have created test table  and it acts as described in my issue above. 
```create table test
(
    id   int auto_increment
        primary key,
    text varchar(255) null
);

INSERT INTO directus.test (id, text) VALUES (1, 'test');
INSERT INTO directus.test (id, text) VALUES (2, 'test2');
INSERT INTO directus.test (id, text) VALUES (3, 'test3');
INSERT INTO directus.test (id, text) VALUES (4, 'test4');
INSERT INTO directus.test (id, text) VALUES (5, 'test5');
INSERT INTO directus.test (id, text) VALUES (6, 'test6');
INSERT INTO directus.test (id, text) VALUES (7, 'test7');
INSERT INTO directus.test (id, text) VALUES (8, 'test8');
INSERT INTO directus.test (id, text) VALUES (9, 'test9');
INSERT INTO directus.test (id, text) VALUES (10, 'test10');

**Comment by urvashithakar** [comment] 2019-11-19 11:23
Hey @konradwww,
This issue is not replicable in the latest version.

**Comment by konradwww** [comment] 2019-11-26 15:40
Hi it doesn't work in the last released version 2.6.0. I have just check it out In development version and there is already fix for it which works, please see here:
[https://github.com/directus/api/pull/1362/commits/e8d0b0dde58eeae32b097ad2580792a6d2d98bb0](https://github.com/directus/api/pull/1362/commits/e8d0b0dde58eeae32b097ad2580792a6d2d98bb0)

so to get it working on v.2.6.0 just paste this snippet, or wait for new api release.

**Comment by bjgajjar** [comment] 2019-11-29 12:14
@konradwww - It is not only in the `develop` branch but it is on `Directus build` too.  Please check [here](https://github.com/directus/directus/blob/master/src/core/Directus/Database/TableGateway/RelationalTableGateway.php#L792) 

That's why we are mentioning that we are not able to reproduce it :)

**Comment by bjgajjar** [comment] 2019-12-26 13:48
As this issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.

**Closed by bjgajjar** 2019-12-26 13:48 UTC
Labels: bug
