### ISSUE TITLE
Parsing environment variables in Docker container

### ISSUE THREAD

**Issue by usbpaul** [directus/api#1344] opened 2019-10-08 13:50 UTC
When running images directus/api:v2.6.0-apache and directus/app:v7.11.0-node in Kubernetes, I run into problems with environment variables that are set in the container and the way they are parsed in /var/www/src/core/Directus/Config/Context.php.
One of the environment variables in the container is:
DIRECTUS_API_PORT_80_TCP => tcp://10.15.247.201:80
A structure of the environment is built in the function `from_map`, which calls `expand`, which recursively calls itself with a target that is being built, using the path segments ('directus', 'api', 'port', '80', 'tcp') in the given case. At some point this recursion results in the target being the value 'tcp://10.15.247.201:80' and the segment '80', which is interpreted numerically, so the 80th element of 'tcp://10.15.247.201:80' is being passed in as by reference in the next recursion.
This leads to: 
<b>Fatal error</b>:  Uncaught Error: Only variables can be passed by reference in /var/www/src/core/Directus/Config/Context.php:39  
Adding  
```
if (is_numeric($segment)) {
  return;
}
```
as the second instruction in `expand` makes things work for me for the moment, but obviously another solution is required.

# Bug Report

## Steps to Reproduce

1. Go to the url of the api interface
2. See error

## Expected Behavior

A JSON response

## Actual Behavior

Error message is seen: `Fatal error:  Uncaught Error: Only variables can be passed by reference in /var/www/src/core/Directus/Config/Context.php:42`

## Technical Details

API and APP running in containers in Kubernetes from images directus/api:v2.6.0-apache and directus/app:v7.11.0-node

**Comment by usbpaul** [comment] 2019-10-08 14:11
Turns out to be a duplicate of [issue 1337](https://github.com/directus/api/issues/1337)

**Comment by bjgajjar** [comment] 2019-10-09 05:09
Duplicate of #1337

**Closed by bjgajjar** 2019-10-09 05:09 UTC
