### ISSUE TITLE
[v2.0.14] Incorrect trim on text input interface for default string

### ISSUE THREAD

**Issue by gnh1201** [directus/api#740] opened 2019-01-25 05:34 UTC
I tried to assign a default value in the text input interface.
It seems that this default field has the string trim. But in a wrong way.
When I type 'ABCDABCD', each one of the characters on both side is cut off and saved as 'BCDABC'.
The problem repeats when you set the default value in the text input.

step by step: 'Admin setting' -> 'Collection and fields' -> choose collection -> choose field -> edit default value in schema tab -> click done -> check saved default value

I am using Firefox 64.0.

**Comment by WellingGuzman** [comment] 2019-01-30 14:44
@gnh1201 can you test using the latest version? I am not unable to replicate this issue.

Do you have custom hooks in your setup?

**Comment by gnh1201** [comment] 2019-01-31 02:30
Could not modify (PATCH) text fields after updated to API v2.0.16.
https://i.imgur.com/RY9UEIa.png
I did not setup with custom hooks.

**Comment by gnh1201** [comment] 2019-01-31 04:55
on https://a.local/_/fields/receipts/currency

execute with v2.0.14:
```
ALTER TABLE `receipts` (invalid query)
   CHANGE COLUMN `currency` `currency` VARCHAR(201) DEFAULT 'KRW'"
```

execute with v2.0.16 (invalid query):
```
ALTER TABLE `receipts`
  CHANGE COLUMN `currency` `currency` VARCHAR DEFAULT 'KRW'
```

maybe, It is a bug (new) of latest version.

**Comment by WellingGuzman** [comment] 2019-02-01 18:07
Hey @gnh1201, Yes it was a bug introduced in the latest version. I add a comment on https://github.com/directus/api/issues/741 notifying that it has been fixed, but it hasn't been released yet.

About this issue, I am still not able to reproduce it.

**Comment by benhaynes** [comment] 2019-02-08 21:48
We have been trying but can still not reproduce this issue. I'll close it for now, but we will re-open if someone is still experiencing this (and can give us some steps to replicate).

**Closed by benhaynes** 2019-02-08 21:48 UTC
Labels: bug, not reproducible
