### ISSUE TITLE
Error uploading file with same name

### ISSUE THREAD

**Issue by benhaynes** [directus/api#499] opened 2018-10-19 19:00 UTC
I upload an image, and then try to upload the same file again... and it gives an error (see below). If I change the file name and try again it works as expected.

**Comment by sergiopoloc** [comment] 2018-10-19 22:59
how can I reproduce the issue? Where is it located in the code?

**Comment by rijkvanzanten** [comment] 2018-10-19 23:07
@WellingGuzman ?

**Comment by WellingGuzman** [comment] 2018-10-24 21:06
I am not able to reproduce this issue, @benhaynes can you give more details on how you are uploading the files? What's the settings on filename?

I have tried with the application and through the API and the new file is created with a new filename.

Also what's the error you are getting?

**Comment by bluesangria** [comment] 2018-10-25 14:08
I ran into the same issue, and didn't think the system was able to rename. I just assumed if the file existed it would mess up. Therefore my need to be able to have sub directories as mentioned in https://github.com/directus/api/issues/509

You can reproduce the error by going to the file library, create new file, either 'select from device', or drag and drop. The file has to be named whatevername (1).ext The first upload will be successful, the thumbnail is broken. The subsequent uploads will fail (cannot overwrite file on server). 

This is with the local storage.

Format being filename<space><number with or without parenthenses><dot>extension.

I've tried:
image (2).png
toto 1.jpg

**Comment by benhaynes** [comment] 2018-10-25 15:40
Thanks @bluesangria ! This will help @WellingGuzman get this resolved for tomorrow's release.

**Comment by bluesangria** [comment] 2018-10-25 21:13
So weird. now it does it regardless of filename. Just upload the same file twice through the file library or the API post to /files w base64 encoding n a filename.

**Comment by WellingGuzman** [comment] 2018-10-26 20:33
Thanks @bluesangria, I was able to reproduce this bug with your example.

**Comment by WellingGuzman** [comment] 2018-10-26 20:39
This issue has been fixed by https://github.com/directus/api/commit/56ea5dfe02c2f1ce91d1d8b8d7cf5e1ed724b2af

**Closed** 2018-10-26 20:39 UTC
Labels: bug, good first issue, hacktoberfest
