### ISSUE TITLE
Collection Listing wrong field type on DB

### ISSUE THREAD

**Issue by davidewego** [directus/api#1662] opened 2020-01-17 15:01 UTC
In directus_role table the field collection_listing has a wrong field type. VARCHAR(255) is too small for a serialized json store in the db so a TEXT field is better.
When populating the collection list, after selecting some collections and saving, it returns an error and this is the reason.

**Comment by bjgajjar** [comment] 2020-01-21 12:21
Duplicate of https://github.com/directus/api/issues/1644

**Closed by bjgajjar** 2020-01-21 12:21 UTC
Labels: bug
