### ISSUE TITLE
WYSIWYG default VARCHAR length error

### ISSUE THREAD

**Issue by joshuaavalon** [directus/api#614] opened 2018-11-28 02:16 UTC
# Bug Report

## Steps to Reproduce

1. Create WYSIWYG field on collection
2. Enter a random name
3. Click `Next` and `Save`

## Expected Behavior

Create a WYSIWYG

## Actual Behavior
Status code 500
```json
{
  "error": {
    "code": null,
    "message": "SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"
  }
}
```

## Other Context & Screenshots

I have check the length is `65534`. Lower the length to `65530` still does not work but `65500` works.

## Technical Details

[Docker](https://github.com/directus/docker/blob/e586fe0f124612deccf4176d3ca6e2b012ed94b5/examples/single-api/docker-compose.yml)
- Database: MySQL 5.7
- Install Method: Docker

P.S. Fresh install

**Comment by rijkvanzanten** [comment] 2018-11-28 02:21
Oh that's weird! We changed it to `65535` so it would fit.. 🤔

**Comment by joshuaavalon** [comment] 2018-11-28 02:29
@rijkvanzanten 

https://stackoverflow.com/questions/13506832/what-is-the-mysql-varchar-max-size

May be it is related to encoding problem?

**Comment by rijkvanzanten** [comment] 2018-11-28 14:56
By the looks of it, it's because MySQL rows have a max limit as well. Having 1 column of 65535 should work, but then every other column will error out :/ 

The only fix here is to change the datatype to `TEXT` from `VARCHAR`. (The app should default to TEXT)

**Comment by rijkvanzanten** [comment] 2018-11-28 14:57
Duplicate of https://github.com/directus/app/issues/1149

**Closed by rijkvanzanten** 2018-11-28 14:57 UTC
Labels: duplicate
