### ISSUE TITLE
Need help with CORS configuration

### ISSUE THREAD

**Issue by next-direction** [directus/api#1605] opened 2019-12-29 16:46 UTC
Hi,

I don't know if CORS is currently buggy or not, but I configured it like this:
```
'cors' => [
    'enabled'         => true,
    'origin'          => array(
        0 => 'https://cc.next-direction.de',
    ),
    'methods'         => array(
        0 => 'GET',
        1 => 'POST',
        2 => 'PUT',
        3 => 'PATCH',
        4 => 'DELETE',
        5 => 'HEAD',
    ),
    'headers'         => array(),
    'exposed_headers' => array(),
    'max_age'         => 600,
    'credentials'     => true,
],
```
As you can see, there is only one allowed origin there, at least as I understand it (https://cc..., which currently doesn't exist, but I wanted to test this before deploying my own app).

When I develop locally I get a **request origin** of "http://localhost:3001".

All requests are still possible. I expected, that requests are only allowed if they are coming from specified allowed origin.
In preflight OPTION call it always says "Access-Control-Allow-Origin: http://localhost:3001" in the **response header**.

I tested this with two different installations, one locally with apache and one on a remote server with nginx.

Do I miss something in the configuration?

Current Directus Version is **8.3.1**

**Comment by bjgajjar** [comment] 2019-12-30 10:45
Duplicate of https://github.com/directus/api/issues/1572. Closing this on a reference to that.

**Closed by bjgajjar** 2019-12-30 10:45 UTC
