### ISSUE TITLE
Server Error After Login

### ISSUE THREAD

**Issue by srjrol** [directus/api#1226] opened 2019-08-28 17:28 UTC
After updating from version Spouting Whale — (190807A) to Spouting Whale — (190807A) my installation broke and I encounter a constant server error after login.  I also tried a  clean install of the latest version with a fresh database but I get the Server Error.  

I installed version Shield — (190827A), using GitVersion in Cpanel to copy the repo.

I used the built-in wizard to create the default API with a new database.  I've included a zip of the files and a copy of the database that was created.

![image](https://user-images.githubusercontent.com/34398302/63877238-c9d08080-c98c-11e9-8025-8c3db087448f.png)

# Bug Report

## Steps to Reproduce

1. Go to Login page
2. Login
3. See error

## Expected Behavior
Login and use the app without error.
## Actual Behavior
The error appears after login and prevents all use of the app.
## Other Context & Screenshots
Error in the log:
> [2019-08-28 02:20:02] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/drivve5/public_html/drivve/src/helpers/app.php:268
- Full Logs:
[error.2019-08-28.log](https://github.com/directus/directus/files/3552101/error.2019-08-28.log)
- SQL Database:
[drivve5_beta.sql.gz](https://github.com/directus/directus/files/3552103/drivve5_beta.sql.gz)
- Directrus Repository (installed): 
https://drive.google.com/open?id=1_lfq-vZJ-u7CnH9ZrF7CP33hvRiV2Sfj

## Technical Details
- Device: Desktop
- OS: Windows 10, Firefox and Chrome
- Web Server:
![image](https://user-images.githubusercontent.com/34398302/63877648-a2c67e80-c98d-11e9-825c-109ccbdf418e.png)
- Install Method: 
![image](https://user-images.githubusercontent.com/34398302/63877587-84f91980-c98d-11e9-8fde-0e27aecdccd5.png)
- Build: Shield — (190827A)

**Comment by srjrol** [comment] 2019-08-29 11:27
I was able to update my database manually using `bin/directus db:upgrade` but I still encounter the same error.

**Comment by benhaynes** [comment] 2019-08-30 16:19
Thanks @srjrol — we'll take a look.

@directus/api-team — just be aware that this is with MariaDB, in case that is part of the culprit.

**Comment by yakou32** [comment] 2019-08-31 05:12
Note that I have the same issue with MySQL 5.6...

**Comment by rijkvanzanten** [comment] 2019-09-02 23:55
@yakou32 Makes sense, Directus requires 5.7+

https://docs.directus.io/getting-started/installation.html#requirements

**Comment by yakou32** [comment] 2019-09-03 06:37
Oops, Sorry for the typo. 
I rechecked, and I have the 5.7 version.

**Comment by bjgajjar** [comment] 2019-09-03 12:33
@srjrol  - I need your help to replicate this issue. I checked in `MariaDB` but not able to reproduce it. I pinged you at slack for further discussion. Let's connect there.

**Comment by bjgajjar** [comment] 2019-09-09 06:15
@srjrol - May I have a screen recorder for your issue?

**Comment by bjgajjar** [comment] 2019-09-30 12:39
As this issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.

**Closed by bjgajjar** 2019-09-30 12:39 UTC
Labels: needs more info
