### ISSUE TITLE
Accepting `id` on entry creation requests

### ISSUE THREAD

**Issue by WoLfulus** [directus/api#508] opened 2018-10-24 02:57 UTC
**Describe the bug**
Post requests to create new entries allows passing `id` field.

**To Reproduce**
1. Manually craft a POST /.../ request passing `id` inside JSON

**Expected behavior**
I don't know if this is by design, but bad users can craft requests and mess up ids inside a table (auto incremented for example).

**Comment by rijkvanzanten** [comment] 2018-10-24 13:49
This is a valid concern. For auto increment collections, in most cases it doesn't make sense to provide your own ID. However, this functionality needs to stay for those who don't use auto increment or use a string based key. 

Do you think this is something that should be blocked / error out @wolfulus?

Thoughts @benhaynes @wellingguzman?

**Comment by benhaynes** [comment] 2018-10-24 14:11
We could put a safeguard to protect from accidental PK submission... such as a parameter flag that allows for submitting a PK. But personally I think it stays as is and developers should learn to use it safely/properly. I know auto-increment INT seems like the default (and I suppose it is) but there are a _lot_ of use cases for custom PKs... SKUs, language codes, migrations from existing datasets, etc.

I'd say that what we have now is _by design_, so I'll close this ticket... but we can (and should) continue to discuss the topic here. If there's a good idea/argument to change this functionality then we can reopen.

**Comment by WellingGuzman** [comment] 2018-10-24 14:23
I want to add something to this, even though this can happen in the database, you are allow to add any value, maybe to prevent this we could add an option (new feature) that disallow to set value to auto-increment fields.

Also we can use the `$create` custom status to prevent write value on new fields, such as the`id`.

**Comment by rijkvanzanten** [comment] 2018-10-24 17:01
Isn't there a use case where you would want to override a certain ID by design?

For example when you delete a record and want to "fill" that gap in IDs with a new record?

**Comment by benhaynes** [comment] 2018-10-24 17:09
It's bad practice to "back fill" an ID, since it should be unique in space (unique) and time (immutable). Though yes, there's always the case for migrated data where an auto-increment PK collection might need to ingest specific IDs.

**Comment by PurpleEdge2214** [comment] 2018-10-25 22:41
I like the idea of being able to specify a uuid as the primary key.

Isn't it possible to create validation of the primary key (any fields) in the backend with Directus? Sorry, I'm a newby don't know much about Directus. If so, the developer should be able to ensure that any value for the primary key can be handled appropriately. 

I personally don't think that Directus should be expected to handle every requirement via the App, but there should be explanation of how to achieve our requirements via the Directus backend.

e.g. Can "filter hooks" be used to validate the primary key on insert?

**Comment by rijkvanzanten** [comment] 2018-10-25 22:43
> Isn't it possible to create validation of the primary key (any fields) in the backend with Directus? Sorry, I'm a newby don't know much about Directus. If so, the developer should be able to ensure that any value for the primary key can be handled appropriately.

That's a valid point! You can set the validation for any field, ID included. That would solve this specific use case.

**Comment by WellingGuzman** [comment] 2018-11-02 22:36
> e.g. Can "filter hooks" be used to validate the primary key on insert?

Absolutely, you can add a custom hook to example `item.products.insert:before` and add custom code that validates the data passed and if it doesn't pass a validation you can throw an exception and the API will catch it.

Read how to use hooks in the docs: https://github.com/directus/docs/blob/master/extensions/hooks.md#using-a-function

**Comment by benhaynes** [comment] 2019-05-20 19:28
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Closed by benhaynes** 2019-05-20 19:28 UTC
Labels: enhancement, question
