### ISSUE TITLE
Changing Password over the app doesn't work

### ISSUE THREAD

**Issue by onlinelessons** [directus/api#1199] opened 2019-08-14 07:25 UTC
I go to admin->users and put in a new clear text password an hit "save". The passwort is hashed and saved in the database. If i try to login with the new password i get the error "invalid user credentials"?
Another thing i want to know: how is the user password encrypted? I would like to set a custom user password over the api. I tried bcrypt but it doesn't match!?
Thanks for your help!

**Comment by onlinelessons** [comment] 2019-08-14 12:06
Directus App Version  7.9.0
Directus API 2.4.0
PHP Version 7.2

**Comment by onlinelessons** [comment] 2019-08-14 13:15
Ok, I think i found the error. If i hash a plaintext password with bcrypt (10 rounds) and save it directly to the database, the authentication works. But if i send this password via payload over the API, it gets hashed again and the authentication doen't work.
If i send a plaintext password over the API via payload, it gets hashed, but the authentication doesn't work. So i think there is a wrong hash function on the API. Maybe that is the problem that i can also not update the password over the app?

**Comment by benhaynes** [comment] 2019-08-14 14:54
Thanks! Could you add your database version too? Are you using MySQL? Is this on Apache?

**Comment by benhaynes** [comment] 2019-08-14 15:30
In case it helps, I've also added some more info to the Docs regarding this:

https://docs.directus.io/guides/auth.html#password-encryption

**Comment by bjgajjar** [comment] 2019-08-19 12:35
@shealavington 

> can we check this please? I've had a look, and all seems fine...

Indeed. It works as expected at our end.

@onlinelessons - May I know the details of your DB? I mean the version and the database management system.

**Comment by onlinelessons** [comment] 2019-08-20 06:36
These are the versions:
![image](https://user-images.githubusercontent.com/47600858/63323229-8a1eee80-c325-11e9-8e50-6b695da867cf.png)

**Comment by shealavington** [comment] 2019-08-20 07:56
https://docs.directus.io/advanced/requirements.html#sql

**Comment by onlinelessons** [comment] 2019-08-20 10:14
Mysql Server Version: 5.7.24-26

**Comment by bjgajjar** [comment] 2019-08-26 09:31
Hey @onlinelessons 

Can we have a screen recorder for this issue? Or let's connect over the slack channel to debug it properly. You can join our channel from [here](https://directus.chat/) and find @binal over there.

**Comment by bjgajjar** [comment] 2019-09-03 11:54
As this issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.

**Closed by bjgajjar** 2019-09-03 11:54 UTC
Labels: bug

**Comment by shartley76** [comment] 2019-10-09 03:04
hi just looking at this thread, I have the exact same issue as described in this ticket. 
MySQL v 8.0.14
PHP v7.2.13
Directus App Version 7.9.0
Directus API 2.4.0

**Comment by bjgajjar** [comment] 2019-10-09 05:00
@shartley76 - We have the latest version 2.6.0. Can you please try to check this with update your version?

**Comment by shartley76** [comment] 2019-10-11 01:02
hi @bjgajjar just tried on latest versions of app and api and I get the same error. When I use bcrypt online to check the hashed password from db it doesnt match, If i generate the same password again via bcrypt online and store the resulting hash in the db then i can login with that user successfully. So looks like the client app when it saves a new password, it doesn't use the same algorithm as logging in does to decrypt?

**Comment by woeterman94** [comment] 2020-04-30 17:26
Sorry to reopen this, but i got the exact change issue. Tried changing the password in the app, but then logging in with the password does NOT work
