### ISSUE TITLE
Some video files become empty upon upload

### ISSUE THREAD

**Issue by nielsvermaut** [directus/api#1055] opened 2019-06-26 15:55 UTC
# Bug Report

Hi,

I've just started using Directus, and I've noticed that certain video files do not get uploaded. There is a file created, but no body is written to it.

I'm using the AWS S3 adapter. I've looked into it with XDebug, but I'm a bit puzzled to how it the file actually gets uploaded. I assume the bug is with the repeated base64_encode and decode done for file uploads. I haven't stepped deeper into it because I'm a bit run up to the CoreServicesProvider.

If you can point me to the design docs or something, where I can read up on why/what is the CoreServicesProvider, I'd might be able to debug and fix this myself.

## Steps to Reproduce

1. Install S3 bundle and configure directus to work with s3
2. Upload following file: https://s3-eu-west-1.amazonaws.com/bbm.customers.bazookas.be/bbm-beer-map/original/Pexels+Videos+1472013.mp4

## Expected Behavior
Exact same file at https://s3-eu-west-1.amazonaws.com/bbm.customers.bazookas.be/bbm-beer-map/assets/Pexels+Videos+1472013.mp4
## Actual Behavior

Empty file

![Screenshot 2019-06-26 at 17 53 12](https://user-images.githubusercontent.com/1325321/60195421-55b61700-983b-11e9-8d83-ca7562fc5a48.png)

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: Debian, Docker
- Web Server: NGINX
- PHP Version: 7.2
- Database: MariaDB:10
- Install Method: cloned from master, created customer docker container

**Comment by shealavington** [comment] 2019-06-26 16:00
I believe this will be fixed for the next release, could you confirm (@hemratna / @bjgajjar) if this was fixed in the linked PR, if so, then this issue can be closed.

Ref: https://github.com/directus/api/pull/1051

**Comment by bjgajjar** [comment] 2019-06-27 04:39
I am closing this issue as it fixed in #1051 and duplicate of #999

**Closed by bjgajjar** 2019-06-27 04:39 UTC
Labels: bug, duplicate
