### ISSUE TITLE
Creating field with datatype "TEXT" on api causes error

### ISSUE THREAD

**Issue by Lapsus** [directus/api#696] opened 2019-01-14 10:55 UTC
# Bug Report

## Steps to Reproduce
1. Create a new database table with an id column/primary key and a column "position" as longtext. Table should not be managed by Directus yet.
2. Fetch collection data for the new table via API. 
3. Merge the fetched data to have the collection managed with Directus.
4. Merge the field definition fetched from the API to make column "position" use the "Map" interface.

## Expected Behavior
Collection and fields are created properly, as the collection is now managed, and the fields provide interface information.

## Actual Behavior
Error: Code: 403 - field "position" does not support length

## Other Context & Screenshots
Other interfaces like status, text or date work well that way. Fetching the collection info via API, modifying the data to make the collection managed and setting the fields to the required interfaces. But it failes for "Map", or "Advanced WYSIWYG".

If length is not used by the longtext datatype, it should either be not provided when fetching collection data or it should be ignored when creating the field. At least in my humble opinion.

Or is this the wrong approach?

**Comment by WellingGuzman** [comment] 2019-01-16 15:01
Hey @Lapsus, this is not a bug, it's a expected behavior. The reason there's an error, it's to warn that no matter the length they provide it won't be useful, we could silently avoid this, but then it could cause issues when the user assumes the length was accepted, when it was actually ignored.

That data is provided as information to let the user know how many character the field takes.

**Comment by Lapsus** [comment] 2019-01-16 15:33
Hmm but it seems quite confusing to me ,if the data structure for the field is different depending on the datatype. 

Maybe this is an issue for the documentation then? As far as i have seen, there is no documentation on how the fields have to be defined depending on datatype/interface etc. Or did i miss that? I think i remember having read some note on fields, but no clear definition on what has to be defined or is optional for the different datatypes.

**Comment by rijkvanzanten** [comment] 2019-01-16 15:38
> But it failes for "Map", or "Advanced WYSIWYG".

It sounds like my that the application might wrongly send the length value, even though it's not being used. @WellingGuzman this might actually be an issue on the application side of things, not the API.

**Comment by Lapsus** [comment] 2019-01-16 15:45
I am fetching and sending back to the API without using the APP.

if that helps. i am creating a setup script that fetches from the collection endpoint and modifies the fetched data to make certain collections managed and to setup the fields according to an external configuration. The modified data structure is then sent back to the API endpoint.

**Comment by rijkvanzanten** [comment] 2019-01-16 15:47
Ahh I see. I think the API might return `length: null` for those fields, but then throws a warning if you send `length: null`. 

I suppose the API should ignore if `length: null` is send for TEXT fields. I think it _should_ return the error when a `length` is provided that something not null, f.e. `length: 200` as that implies that the user made a mistake

**Comment by benhaynes** [comment] 2019-01-16 16:02
So is this working as expected? Should we update the Docs accordingly and then close this?

**Comment by WellingGuzman** [comment] 2019-01-16 17:39
It's working as expected, It's a confusion, or missing information what that means. There are some mysql types that doesn't require length, even though some return an actual length, such as `TEXT`.

Ignoring `length` can be confusing as well, when the field doesn't even allow it.

I prefer removing the length from these data types than ignoring them when they exists.

**Comment by rijkvanzanten** [comment] 2019-01-16 19:06
But that means that the API won't accept it's own output as it's input. If the API is returning `length: null` for `TEXT` type fields, it should accept `length: null` as input for those fields as well

**Comment by WellingGuzman** [comment] 2019-01-18 16:03
I believe Input shouldn't reflect output, or be 100% compatible. While the field has length, the length cannot be changeable, that's why is not allowed in the input. returning `null` could means it has no `length`.

We can discuss what we can do here to avoid the confusion.

I will close this as this is not a bug nor a feature request.

**Closed by WellingGuzman** 2019-01-18 16:03 UTC
