### ISSUE TITLE
internal server error on m2m 

### ISSUE THREAD

**Issue by kjj77** [directus/api#684] opened 2018-12-11 15:22 UTC
# Bug Report
I'm having problems in m2m relational field, a message from the backend ("Internal Server Error") when trying to attach multiple files to my items through a junction table.

This is the relation :

![image](https://user-images.githubusercontent.com/34485550/49808663-61d5fd80-fd5d-11e8-9271-aca1fa6320c5.png)

for the field in the _items_ table. I created the junction table. I do not remember if this table was created automatically in Directus 6, but I had the same field and it worked. This is how it looked in Directus 6 : 

![image](https://user-images.githubusercontent.com/34485550/49810183-efffb300-fd60-11e8-8e08-bb833a2c566b.png)

## Expected Behavior

Saving the item without errors.

## Actual Behavior

Internal server error message blocks saving the item.

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome 70.0.3538.110
- Directus App: 7.0.11
- Directus API: 7.0.11
- Install Method: cloned `master` branch

**Comment by WellingGuzman** [comment] 2019-01-04 21:17
Hey @kjj77, can you share an schema that we can use to reproduce this issue? Also can you check if there's any logs in your `logs` directory?

**Comment by kjj77** [comment] 2019-01-09 10:53
Hi @WellingGuzman,

what kind of file do you need exactly ? A MySQL export of the entire base ? 
In case, I can give you access to the interface online with a user created for you.

**Comment by WellingGuzman** [comment] 2019-01-09 13:11
@kjj77 I want to see if you have any logs file related to this error in your `logs` directory and your mysql database dump, so I can test it locally.

Giving me access will be helpful, but if I can't see how the relationship are set and what's the actual error I cannot do very much to find the issue.

**Comment by benhaynes** [comment] 2019-01-18 17:16
Hey @kjj77 — any update on this? I'd love to get it resolved/closed!

Thanks...

**Comment by benhaynes** [comment] 2019-01-28 21:15
Hey @kjj77 — no one has been able to reproduce this on our side. If you're still seeing this issue and can provide a database dump we'll re-open and take a look!

**Comment by swaipdev** [comment] 2019-04-03 08:27
Hi guys,

sorry for being late. I first decided to stick to Directus 6, but now that I have a little bit more time I'm trying again to move to Directus 7, but I'm still stumbling on the same bugs: this one of the m2m field, and the famous logo bug in the global settings (see for example: https://github.com/directus/directus/issues/2252).

I started clean from the docker compose single api version :

https://github.com/directus/docker/tree/master/examples/single-api

on a AWS instance. 
I recreated the two tables with the relationship described. Now I get this error :

![image](https://user-images.githubusercontent.com/48906229/55462878-155a4a80-55f8-11e9-848c-564185655d19.png)
 
In console, I have an invalid field name error : 

![image](https://user-images.githubusercontent.com/48906229/55462961-4dfa2400-55f8-11e9-88e4-7595394a7b5e.png)

I actually managed to get the attachment to appear before, but still the relation was not saved (not even in the junction table).

Since it's the first time I use the docker version, how would I make a dump of the database for you to inspect ? From mysql demon on SSH ?

Thanks,

Carlo

**Comment by swaipdev** [comment] 2019-04-08 07:59
Hi guys,
this is the mysqldump, 
can you take a look at it ? 
I'm probably doing something wrong with these m2m fields, but in Directus 6 I managed to make them work and I definitely want to move to Directus 7.

Thanks,
Carlo

[somedb.zip](https://github.com/directus/api/files/3053236/somedb.zip)

**Comment by bjgajjar** [comment] 2019-04-18 13:23
Hi @swaipdev,

I've checked your database and found a wrong configuration of relation.
You've created a field `Pieces Jointes` under `Items` collection. The issue is with `Listing View Preferences` configuration, where you've used the default filter which is `name` and that field is not set up under the related collection. That's why the API is showing an error.
Here is the screenshot for reference:

![Screenshot_1](https://user-images.githubusercontent.com/19200178/56363941-fcae7f00-620a-11e9-9f6a-b391fbab558f.png)

I'm closing this issue as it is not a bug but wrong configuration. Kindly let me know if you can not solve the issue at your end. Thanks.

**Closed by bjgajjar** 2019-04-18 13:23 UTC
Labels: bug, not reproducible

**Comment by kjj77** [comment] 2019-04-23 10:22
Hi guys,

thanks it works, guess I've just some hard time understanding the new
interface, most notably in the relation fields.

Carlo
