### ISSUE TITLE
Bin installation doesn't create user

### ISSUE THREAD

**Issue by polgiron** [directus/api#920] opened 2019-04-29 11:14 UTC
# Bug Report

## Steps to Reproduce

1/ Install and set up directus from the digital ocean droplet, I have upgraded directus from the latest master.
2/ Create a new DB in mysql
3/ Create a new directus API
`bin/directus install:config -n <new-database-name> -u <mysql-user> -p <mysql-password> -N <project-name>`
(I'm using the directus user)
`bin/directus install:database -N <project-name>`
`bin/directus install:install -e admin@email.com -p password -t <project-name> -N <project-name>`
4/ Add the new project to the config.s at `/var/www/directus/public/admin/config.js`

## Expected Behavior

Be able to login

## Actual Behavior

I can't seem to be able to login to the new API with these credentials: admin@email.com // password

`POST https://api.paulgiron.com/<project-name>/auth/authenticate 404 (Not Found)`
`Wrong username and/or password`

It's worth noticing that it used to work before I've updated from master yesterday

## Technical Details

- Device: desktop
- OS: macos
- Browser: chrome

**Comment by rijkvanzanten** [comment] 2019-04-29 14:20
> Install and set up directus from the digital ocean droplet

You mean the one-click install? When opening the admin app on a fresh install of this, you should be able to install the API through the UI. Any reason why you use the bin tool directly?

**Comment by polgiron** [comment] 2019-04-29 14:22
it is working fine with the default API, I am adding more API to it for my different projects, it used to work fine I have already added another one in the past, but I have tried yesterday after updating from master and I can't log in anymore to the new created one :(

**Comment by rijkvanzanten** [comment] 2019-04-29 14:23
Gotcha 👍 

Did you create a new database for these new projects too? Can you confirm the API actually created the api config file and populated this new database?

**Comment by polgiron** [comment] 2019-04-29 14:31
Yes I am creating a new DB first in the mysql prompt: `CREATE DATABASE photol;`
I have just double checked, yes the config file has been generated, and the DB seems to have been populated as well:
```
mysql> show tables;
+-----------------------------+
| Tables_in_photol            |
+-----------------------------+
| directus_activity           |
| directus_activity_seen      |
| directus_collection_presets |
| directus_collections        |
| directus_fields             |
| directus_files              |
| directus_folders            |
| directus_migrations         |
| directus_permissions        |
| directus_relations          |
| directus_revisions          |
| directus_roles              |
| directus_settings           |
| directus_user_roles         |
| directus_users              |
+-----------------------------+
```

(my new project is called photol)

**Comment by rijkvanzanten** [comment] 2019-04-29 14:33
Could you double check that the user was created as well? Did the password get hashed correctly?

**Comment by polgiron** [comment] 2019-04-29 14:39
Using phpmyadmin I can see that the table `directus_users` is actually empty in the database photol

**Comment by rijkvanzanten** [comment] 2019-04-29 14:41
Are there any errors logged in the `/logs` folder?

**Comment by polgiron** [comment] 2019-04-29 14:47
I can see a few yes, maybe it is about permissions?

https://pastebin.com/9Sk0wHDE

**Comment by rijkvanzanten** [comment] 2019-04-29 14:48
Hmm those look like the regular "someone tried to login with the wrong credentials" error

**Comment by polgiron** [comment] 2019-04-29 14:54
Here is the all file, I hope it will be helpful: https://pastebin.com/wGYTy944

**Comment by bjgajjar** [comment] 2019-04-30 07:00
Closed in #922

**Comment by polgiron** [comment] 2019-05-05 11:08
Hey guys! thank you so much for fixing this issue so fast, but I have pulled master today and I still can't log in after running the bin install command, the directus_users table is still empty :(

>

**Comment by alrick** [comment] 2019-05-13 11:58
I second this, atm we can't create admin user with `bin/directus install:install`

**Comment by bjgajjar** [comment] 2019-05-30 13:21
@polgiron Please try with a fresh clone and try again. As I checked it again but not able to replicate!

**Comment by sarneeh** [comment] 2019-07-03 20:51
@bjgajjar I have the same issue, even with a fresh clone right now. Using `bin/directus install:install` I don't get any new user.

**Comment by sarneeh** [comment] 2019-07-03 20:55
@bjgajjar This still doesn't work with a fresh clone right now. Actually, it works for the initial project, but when you'll create a new one and use `install:install` with `-N`, the database is getting populated, but not the users.

**Comment by sarneeh** [comment] 2019-07-03 21:05
https://github.com/directus/api/blob/289f4759ca10ecd62927f9c4fb23e3b55bbc596a/src/core/Directus/Console/Modules/InstallModule.php#L201-L220

The problem is in the `!$user->userExists($data['user_email'])` statement, as `User` - as I can see - works only with the default project, it completely ignores separate projects.

**Closed** 2019-07-04 07:20 UTC
Labels: bug
