### ISSUE TITLE
fields=created_on returns internal server error

### ISSUE THREAD

**Issue by beac0n** [directus/api#685] opened 2019-01-06 15:47 UTC
# Bug Report

## Steps to Reproduce

1. create collection with created_on, created_by fields
2. make query with fields=created_on

## Expected Behavior

it should return all results, but only the created_on field

## Actual Behavior

it returns { error: { code: null, message: 'Internal Server Error' } } }

## Technical Details

latest docker api image (2.0.13)

**Comment by rijkvanzanten** [comment] 2019-01-06 22:37
Hey @beac0n! Can you check if the error log contains the same error as mine in https://github.com/directus/api/issues/687?

**Comment by rijkvanzanten** [comment] 2019-01-06 22:37
I'm wondering if we have the same problem or if it's caused by something else

**Comment by WellingGuzman** [comment] 2019-01-07 14:13
This seems to be a bug already fixed by https://github.com/directus/api/commit/83f5b5b982fec56e251602a843cab608b0f252c1.

I will close this as it potentially seems the same bug.

**Closed by WellingGuzman** 2019-01-07 14:13 UTC
Labels: bug
