### ISSUE TITLE
possible DECIMAL range value will automatically been changed to default 10,0 when saving number field 

### ISSUE THREAD

**Issue by prettyGitty** [directus/api#853] opened 2019-03-26 14:17 UTC
# Bug Report
When altering any options of a decimal number field it will automatically set the choosen "Length" to the default range value of 10,0.

Afterwards all right digits within this table column will be changed  (i.e percentage values like 0.61 will be changed to 1) and are therefor lost.

## Steps to Reproduce

1. Go to any number field with the datatype DECIMAL
2. Change anything or nothing, but click on save
3. If "Length" has been a custom range value, it will be set back to the default 10,0 now

## Expected Behavior
Never change the choosen decimal range value, since all the saved digits on the right side or numbers with more than 10 digits on the left side are gone afterwards

## Actual Behavior
Sets back the range value of decimal number fields to its default 10,0 everytime when it is saved

## Technical Details

- Device: Virtual Server
- OS: Ubuntu 16.04
- Web Server: Apache 2.4.18
- PHP Version:  v7.1.27
- Database: MySQL Ver 14.14 Distrib 5.7.25
- Install Method: cloned `master` branch

**Comment by theharshin** [comment] 2019-04-22 07:50
@rijkvanzanten The issue is with API. Here are the screenshots from the api request:

Request:
![image](https://user-images.githubusercontent.com/7118937/56489963-2b756f80-6501-11e9-8344-e9f05b6a6bd8.png)


Response:
![image](https://user-images.githubusercontent.com/7118937/56489983-3af4b880-6501-11e9-95b4-24bbd71c37f5.png)


@bjgajjar Lets have a look at this 🙂

**Comment by bjgajjar** [comment] 2019-04-29 13:45
Closed in #918

**Closed** 2019-04-29 13:45 UTC
Labels: bug
