### ISSUE TITLE
Add Title property to collection

### ISSUE THREAD

**Issue by yarick2000** [directus/api#1323] opened 2019-09-27 13:19 UTC
# Feature Request
Could you guys please add the Title property to collection, so in case if it's specified it will be displayed in the app instead of Name

## What problem does this feature solve?
Sometimes the collection name can be unclear to some of the CMS users or it can be too long and so it's better to show something short for users, especially in cases when DB was adopted from the legacy project. The 'Note' field is useful, but not in all cases.

## How do you think this should be implemented?
The new field Title in case if specified should be used everywhere in the App instead of Name field. The value of the Name field can be shown, for example, when user hovering with mouse over the Title, and of course on Collections & Fields page as well.

## Would you be willing to work on this?
I'm not sure if I'm competent enough for that.

**Comment by benhaynes** [comment] 2019-09-27 13:44
Thanks @yarick2000 — this is actually a duplicate of: https://github.com/directus/app/issues/422

We're adding translations to table/column names so that you can override the database names as needed. In the meantime, you can use the `nav_override` role option to accomplish this.

**Closed by benhaynes** 2019-09-27 13:44 UTC

**Comment by yarick2000** [comment] 2019-09-27 13:46
Ah, ok, thank you
