### ISSUE TITLE
Use `/` as document root

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#596] opened 2018-11-18 17:33 UTC
Can we allow the root of the api repo to be used as document root? Certain shared hosting providers don't allow folders to be set as document root

**Comment by WellingGuzman** [comment] 2018-11-21 14:33
I will look into this, but I don't understand what this means isn't root also a directory? I am curious because I've never experienced this before.

**Comment by rijkvanzanten** [comment] 2018-11-21 14:50
Someone on slack pointed out that certain (cheap) shared hosting providers only have 1 root directory of the server (often called `public_html`). This means that directus is only available under `/public/` instead of `/`. Is there anything we can do to work on `/` in those cases?

**Comment by aught13** [comment] 2018-11-28 01:44
I'll say that I'm experiencing this with my hosting through Hostwinds They have an install for an older version of directus but I'm unable to make that work for me at all. I get error 108 when I point to mydomain.com/directus/public

**Comment by treechime** [comment] 2018-12-13 05:45
Correct me if I'm wrong, but another use case for this is when I don't want to install Directus to the root of the server?

My current v6 installs are multiple subdirectories deep and I'm now trying to work out how to maintain the same url structure to access the app in v7.

e.g. `/directory/subdirectory/directus` instead of `/directory/subdirectory/directus/public/admin`

**Comment by rijkvanzanten** [comment] 2018-12-13 12:47
Yeah it kinda looks that way in my comment (my bad) but what I meant is that we want a way where `public` isn't a part of the URL 🙂

**Comment by treechime** [comment] 2018-12-13 23:12
Yeah, exactly. That's definitely a deal breaker on me upgrading to v7 for the moment. :(

**Comment by benhaynes** [comment] 2019-01-06 18:31
@WellingGuzman @rijkvanzanten — is this a duplicate of https://github.com/directus/api/issues/636 ?

**Comment by benhaynes** [comment] 2019-01-30 15:27
Duplicate of: https://github.com/directus/api/issues/636

Merging this in so API can support _any_ `base_path`.

**Closed by benhaynes** 2019-01-30 15:27 UTC
Labels: question
