### ISSUE TITLE
Can't get multi-tenancy to work

### ISSUE THREAD

**Issue by thepurpleblob** [directus/api#941] opened 2019-05-08 16:45 UTC
# Bug Report

Set up second project using what instructions I could find but can find no way to select it in the Admin app. 

## Steps to Reproduce

1. Create default installation following the default prompts... works
2. Create a second database
3. Follow steps here - https://docs.directus.io/advanced/api/configuration.html - using '-N' with new name 
4. Update public/admin/config.php for the second project

Logged in to the admin app

## Expected Behavior

Expected some place to select different project

## Actual Behavior

I couldn't see anywhere to select the project the admin app is administering. 

## Technical Details

- Device: Desktop
- OS: Ubuntu 18.04
- Web Server: Apache 2.4
- PHP Version: 7.2.17
- Database: MariaDB 10.1.38
- Install Method: As above

**Comment by rijkvanzanten** [comment] 2019-05-08 20:43
I'll close this as it's a duplicate of #920.

**Closed by rijkvanzanten** 2019-05-08 20:43 UTC
