### ISSUE TITLE
V8 fresh install is broken

### ISSUE THREAD

**Issue by everyx** [directus/api#1497] opened 2019-11-28 11:11 UTC
# Bug Report

## Steps to Reproduce

1. Go to http://project.com/admin from new fresh install
2. Follow step to create project and we get `api[].ERROR: Error: Undefined class constant 'TYPE_STRIN' in /var/www/migrations/install/20180220023208_create_files_table.php:120`
3. Manually fix `TYPE_STRIN` to `TYPE_STRING` and continue, install success
4. Go to login, we get `api[test].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL query. in /var/www/src/core/Directus/Database/TableGateway/BaseTableGateway.php:755`

## Technical Details

- Device: Desktop
- OS: Docker Desktop on Windows 10
- Web Server: Caddy on Docker
- PHP Version: 7.3
- Database: MySQL 8
- Install Method: cloned develop branch

## API Logs

```shell
[2019-11-28 09:09:29] api[].ERROR: Error: Undefined class constant 'TYPE_STRIN' in /var/www/migrations/install/20180220023208_create_files_table.php:120
Stack trace:
#0 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(124): CreateFilesTable->change
#1 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(375): Phinx\Migration\Manager\Environment->executeMigration
#2 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(351): Phinx\Migration\Manager->executeMigration
#3 /var/www/src/core/Directus/Util/Installation/InstallerUtils.php(237): Phinx\Migration\Manager->migrate
#4 /var/www/src/core/Directus/Util/Installation/InstallerUtils.php(204): Directus\Util\Installation\InstallerUtils::runMigrationAndSeeder
#5 /var/www/src/core/Directus/Services/ProjectService.php(120): Directus\Util\Installation\InstallerUtils::createTables
#6 /var/www/src/endpoints/ProjectsCreate.php(17): Directus\Services\ProjectService->create
#7 [internal function]: Directus\Api\Routes\ProjectsCreate->__invoke
#8 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#9 /var/www/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#10 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke
#11 /var/www/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#12 /var/www/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#13 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->__invoke
#14 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#15 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#16 [internal function]: Slim\DeferredCallable->__invoke
#17 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#18 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#19 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#20 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#21 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run
#22 /var/www/public/index.php(5): Directus\Application\Application->run [] []
```

```shell
[2019-11-28 09:17:59] api[test].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL query. in /var/www/src/core/Directus/Database/TableGateway/BaseTableGateway.php:755
Stack trace:
#0 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(209): Directus\Database\TableGateway\BaseTableGateway->executeSelect
#1 /var/www/src/core/Directus/Database/TableGateway/DirectusUserSessionsTableGateway.php(68): Zend\Db\TableGateway\AbstractTableGateway->selectWith
#2 /var/www/src/core/Directus/Services/UserSessionService.php(75): Directus\Database\TableGateway\DirectusUserSessionsTableGateway->fetchSession
#3 /var/www/src/endpoints/Auth.php(125): Directus\Services\UserSessionService->find
#4 /var/www/src/endpoints/Auth.php(73): Directus\Api\Routes\Auth->storeCookieSession
#5 [internal function]: Directus\Api\Routes\Auth->authenticate
#6 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#7 /var/www/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#8 /var/www/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->__invoke
#9 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#10 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#11 [internal function]: Slim\DeferredCallable->__invoke
#12 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#13 /var/www/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#14 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#15 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#16 [internal function]: Slim\DeferredCallable->__invoke
#17 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#18 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#19 /var/www/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#20 /var/www/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#21 /var/www/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#22 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#23 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#24 [internal function]: Slim\DeferredCallable->__invoke
#25 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#26 /var/www/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#27 /var/www/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#28 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#29 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#30 [internal function]: Slim\DeferredCallable->__invoke
#31 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#32 /var/www/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#33 [internal function]: RKA\Middleware\IpAddress->__invoke
#34 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#35 [internal function]: Slim\DeferredCallable->__invoke
#36 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#37 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#38 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#39 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#40 [internal function]: Slim\DeferredCallable->__invoke
#41 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#42 /var/www/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#43 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#44 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#45 [internal function]: Slim\DeferredCallable->__invoke
#46 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#47 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#48 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#49 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#50 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run
#51 /var/www/public/index.php(5): Directus\Application\Application->run [] []
```

**Comment by everyx** [comment] 2019-11-28 12:10
@bjgajjar I just do this fix manually, but couldn't login

> Go to login, we get api[test].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL query. in /var/www/src/core/Directus/Database/TableGateway/BaseTableGateway.php:755

**Comment by bjgajjar** [comment] 2019-11-28 13:49
Are you getting the same error?

**Comment by everyx** [comment] 2019-11-28 14:05
> Are you getting the same error?

Yes, I just try the newest develop branch minutes ago, and it doesn't have fixed.

There's are two error at this issues, and the commit 3f62a49 fix the first one, the second one: 

> Go to login, we get
> `api[test].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL query. in /var/www/src/core/Directus/Database/TableGateway/BaseTableGateway.php:755`

![image](https://user-images.githubusercontent.com/1665522/69812259-b1d9f880-122a-11ea-9a6d-f7d55ebdb17e.png)

logs:

```
[2019-11-28 14:01:21] api[test].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL query. in /var/www/src/core/Directus/Database/TableGateway/BaseTableGateway.php:755
Stack trace:
#0 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(209): Directus\Database\TableGateway\BaseTableGateway->executeSelect
#1 /var/www/src/core/Directus/Database/TableGateway/DirectusUserSessionsTableGateway.php(68): Zend\Db\TableGateway\AbstractTableGateway->selectWith
#2 /var/www/src/core/Directus/Services/UserSessionService.php(75): Directus\Database\TableGateway\DirectusUserSessionsTableGateway->fetchSession
#3 /var/www/src/endpoints/Auth.php(125): Directus\Services\UserSessionService->find
#4 /var/www/src/endpoints/Auth.php(73): Directus\Api\Routes\Auth->storeCookieSession
#5 [internal function]: Directus\Api\Routes\Auth->authenticate
#6 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#7 /var/www/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#8 /var/www/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->__invoke
#9 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#10 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#11 [internal function]: Slim\DeferredCallable->__invoke
#12 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#13 /var/www/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#14 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#15 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#16 [internal function]: Slim\DeferredCallable->__invoke
#17 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#18 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#19 /var/www/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#20 /var/www/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#21 /var/www/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#22 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#23 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#24 [internal function]: Slim\DeferredCallable->__invoke
#25 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#26 /var/www/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#27 /var/www/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#28 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#29 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#30 [internal function]: Slim\DeferredCallable->__invoke
#31 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#32 /var/www/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#33 [internal function]: RKA\Middleware\IpAddress->__invoke
#34 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#35 [internal function]: Slim\DeferredCallable->__invoke
#36 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#37 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#38 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#39 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#40 [internal function]: Slim\DeferredCallable->__invoke
#41 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#42 /var/www/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#43 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#44 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#45 [internal function]: Slim\DeferredCallable->__invoke
#46 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#47 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#48 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#49 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#50 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run
#51 /var/www/public/index.php(5): Directus\Application\Application->run [] []
[2019-11-28 14:01:23] api[test].ERROR: Failed generating the SQL query. [] []
[2019-11-28 14:01:34] api[test].ERROR: Failed generating the SQL query. [] []
[2019-11-28 14:01:44] api[test].ERROR: Failed generating the SQL query. [] []
[2019-11-28 14:01:54] api[test].ERROR: Failed generating the SQL query. [] []
[2019-11-28 14:02:04] api[test].ERROR: Failed generating the SQL query. [] []
[2019-11-28 14:02:14] api[test].ERROR: Failed generating the SQL query. [] []
[2019-11-28 14:02:24] api[test].ERROR: Failed generating the SQL query. [] []
[2019-11-28 14:02:34] api[test].ERROR: Failed generating the SQL query. [] []
[2019-11-28 14:02:44] api[test].ERROR: Failed generating the SQL query. [] []
[2019-11-28 14:02:54] api[test].ERROR: Failed generating the SQL query. [] []
[2019-11-28 14:03:04] api[test].ERROR: Failed generating the SQL query. [] []
```

**Comment by everyx** [comment] 2019-11-29 00:39
@bjgajjar Can you duplicate it?

**Comment by bjgajjar** [comment] 2019-11-29 05:11
@everyx - I am able to fresh install the `Directus` using `develop` branch. Let's connect to slack channel for the further discussion.

**Comment by everyx** [comment] 2019-11-29 05:44
> @everyx - I am able to fresh install the `Directus` using `develop` branch. Let's connect to slack channel for the further discussion.

Hi, my member ID is UN49LQY05, how to send message to you in slack?

**Comment by bjgajjar** [comment] 2019-11-29 05:46
You can connect in our slack channel from [here](https://directus.chat) and find me *@binal* over there.

**Comment by everyx** [comment] 2019-11-29 05:54
> _@binal_

Great, I am trying to reinstall from the develop branch now and if get this error again, I'll contact you via slack, thanks. :)

**Comment by everyx** [comment] 2019-11-29 06:16
> > _@binal_
> 
> Great, I am trying to reinstall from the develop branch now and if get this error again, I'll contact you via slack, thanks. :)

After refresh install the develop branch, login work fine, thanks. 😎

**Comment by everyx** [comment] 2019-11-29 07:41
@bjgajjar I have reproduce it, it's look like a app bug, when I install success, remove database and reinstall directus again, it's happened, and when I click "clear site data" and session storage in chrome dev tool, It will work again, should we treat it as a bug of APP?

**Comment by benhaynes** [comment] 2019-11-29 16:22
Thoughts @rijkvanzanten ?

**Comment by rijkvanzanten** [comment] 2019-11-29 16:43
The app will ping the APIs `/:project/` endpoint to retrieve the project name / logo etc. It will also use the `public` flag that that endpoint returns to check if the user is currently authenticated. It sounds to me like there's something going on in the API when pinging the `/:project/` endpoint with a invalid cookie (that used to be valid on the same project name)

**Comment by rijkvanzanten** [comment] 2019-11-29 16:43
The app itself can't read the cookie, so if the api returns something unexpected based on a wrong cookie state, there's nothing the app could've done to prevent that

**Comment by rijkvanzanten** [comment] 2019-11-29 16:54
Duplicate of https://github.com/directus/api/issues/1473

**Closed by rijkvanzanten** 2019-11-29 16:54 UTC
Labels: bug
