### ISSUE TITLE
Password not encrypted after changing it

### ISSUE THREAD

**Issue by Htbaa** [directus/api#970] opened 2019-05-22 13:53 UTC
Hi,

I just installed Directus App and API. Added a new project, deployed schema.sql to the new database. After changing the password of the default admin user I can no longer login. Inspecting the database the password is saved unencrypted, causing login to fail.

This was on Directus 7.4.0.

**Comment by rijkvanzanten** [comment] 2019-05-22 13:54
@bjgajjar Even though I can't reproduce it (yet), can we make sure somehow that this doesn't happen in any case? If the hashing fails for some reason, the API should always error out.

A password should never make it to the database in plain text.

**Comment by bjgajjar** [comment] 2019-05-22 14:06
@rijkvanzanten 

Agree with you! This is not reproducible! Password will always store with Hash encryption.

**Comment by rijkvanzanten** [comment] 2019-05-22 14:12
(some of the replies didn't transfer over, see https://github.com/directus/app/issues/1656)

**Comment by rijkvanzanten** [comment] 2019-05-22 14:33
@Htbaa the `schema.sql` file seems to be outdated. Running the DB Upgrade from the admin settings menu should solve this for you. We'll get that backup schema.sql updated

**Comment by Htbaa** [comment] 2019-05-22 14:38
But the unhashed password was after I updated the account through the app. Or is it because of a schema miss-match that it's not possible to save a hashed password?

**Comment by rijkvanzanten** [comment] 2019-05-22 14:52
The schema.sql doesn't use the correct field type for the password field it seems. Installing through the normal install flow populates the database with the correct values. Running the DB upgrade from the admin settings should bump the old installation to the current values.

**Comment by christianrr** [comment] 2019-05-23 09:07
I have a similar issue: If I change the password of a user in the "Edit profile" page, the user can no longer login any more.

I can confirm that the changed password is encrypted in the database, however login with the changed password doesn't work...

I copied the password from a text file in order to avoid spelling issues.

**Comment by bjgajjar** [comment] 2019-05-24 09:12
Hello @christianrr 

Kindly remove the `interface` folder from `/public/extensions/core`  from `API` to resolve this issue.

**Comment by christianrr** [comment] 2019-05-27 09:32
@bjgajjar Thanks for the hint, for me it was sufficient to delete the `passwords `interface from `/public/extensions/core`

**Comment by bjgajjar** [comment] 2019-05-29 05:58
@Htbaa  Did you able to resolve the issue? Kindly let us know!

**Comment by Htbaa** [comment] 2019-05-29 07:29
@bjgajjar I haven't tried the offered solution. I decided to checkout the latest tagged version which also solved some other weird issues, but haven't tried changing passwords yet though,

**Comment by bjgajjar** [comment] 2019-05-29 09:10
Please check that once and let us know if the issue occurs still! So we can close it.

**Comment by bjgajjar** [comment] 2019-06-04 13:03
This is not replicated in the latest version so closing this. Feel free to reopen :)

**Closed by bjgajjar** 2019-06-04 13:03 UTC
Labels: not reproducible
